#!/usr/bin/env python3
"""Generate Physics/Cap8.lean: the capped pentagonal bipyramid (8 particles,
18 bonds) showing E_min(8) <= -18. Radicals: s5, t as in bipyr7, plus r2 = sqrt 2.
The cap point sits over face (pb0, pb1, pb5)."""
import sympy as sp, math

s5, t, r2 = sp.symbols("s5 t r2", positive=True)
G = [r2**2 - 2, t**2 - (10 - 2*s5), s5**2 - 5]
S5, T, R2 = "Real.sqrt 5", "Real.sqrt (10 - 2 * Real.sqrt 5)", "Real.sqrt 2"

def redq(e):
    qs, r = sp.reduced(sp.expand(e), G, r2, t, s5, order='lex')
    while len(qs) < 3:
        qs.append(sp.Integer(0))
    return qs, sp.expand(r)

def leanify(e):
    s = sp.sstr(sp.nsimplify(e), full_prec=False)
    s = s.replace("**", "^").replace("s5", "@A@").replace("r2", "@C@").replace("t", "@B@")
    s = s.replace("@A@", f"({S5})").replace("@B@", f"({T})").replace("@C@", f"({R2})")
    return s

A = sp.Matrix([(5+s5)*t/20, 0, 0])
B = sp.Matrix([s5*t/20, (1+s5)/4, 0])
P2 = sp.Matrix([-(5+3*s5)*t/40, sp.Rational(1,2), 0])
P3 = sp.Matrix([-(5+3*s5)*t/40, sp.Rational(-1,2), 0])
P4 = sp.Matrix([s5*t/20, -(1+s5)/4, 0])
C5 = sp.Matrix([0, 0, s5*t/10])
C6 = sp.Matrix([0, 0, -s5*t/10])
n = (B-A).cross(C5-A)
n = sp.Matrix([redq(x)[1] for x in n])
P7 = (A+B+C5)/3 + sp.Rational(2,3)*r2*n
P7 = sp.Matrix([redq(x)[1] for x in P7])
pts_sym = [A, B, P2, P3, P4, C5, C6, P7]

BONDS = [(0,1),(1,2),(2,3),(3,4),(0,4),
         (0,5),(1,5),(2,5),(3,5),(4,5),
         (0,6),(1,6),(2,6),(3,6),(4,6),
         (0,7),(1,7),(5,7)]
NONBONDS = [(0,2),(0,3),(1,3),(1,4),(2,4),(5,6),(2,7),(3,7),(4,7),(6,7)]

def dist2(i, j):
    d = pts_sym[i] - pts_sym[j]
    return sp.expand(d.dot(d))

def lc(qs):
    terms = []
    for q, name in zip(qs, ["hr2sq", "ht5sq", "hs5sq"]):
        if q != 0:
            terms.append(f"({leanify(q)}) * {name}")
    return " + ".join(terms) if terms else "(0 : ℝ) * hs5sq"

# pb0..pb6 strings must match the Bipyramid7.lean definitions exactly
# (the `show` step relies on syntactic-up-to-unfolding defeq, no ring normalization)
pts_str = [
    (f"(5 + {S5}) * {T} / 20", "0", "0"),
    (f"{S5} * {T} / 20", f"(1 + {S5}) / 4", "0"),
    (f"-((5 + 3 * {S5}) * {T} / 40)", "1 / 2", "0"),
    (f"-((5 + 3 * {S5}) * {T} / 40)", "-(1 / 2)", "0"),
    (f"{S5} * {T} / 20", f"-((1 + {S5}) / 4)", "0"),
    ("0", "0", f"{S5} * {T} / 10"),
    ("0", "0", f"-({S5} * {T} / 10)"),
    tuple("0" if x == 0 else leanify(x) for x in pts_sym[7]),
]

def show_expr(i, j):
    (xi, yi, zi), (xj, yj, zj) = pts_str[i], pts_str[j]
    return (f"(({xi} : ℝ) - ({xj}))^2 + (({yi} : ℝ) - ({yj}))^2 "
            f"+ (({zi} : ℝ) - ({zj}))^2")

def pname(i, j):
    return f"pb{i}" if i < 7 else "pb7"

L = []
L.append("import Physics.Bipyramid7")
L.append("")
L.append("set_option linter.style.header false")
L.append("set_option maxHeartbeats 1000000")
L.append("")
L.append("/-!")
L.append("# `E_min(8) ≤ −18`: the capped pentagonal bipyramid")
L.append("")
L.append("Attach an eighth particle over the face `(pb0, pb1, pb5)` of the unit-edge")
L.append("pentagonal bipyramid — a regular tetrahedron cap. All 18 bonds are unit, the ten")
L.append("remaining pairs are `≥ √(4/3)` away, so the configuration is hard-core and carries")
L.append("36 ordered contacts: `E ≤ −18` for eight particles. Machine-generated by")
L.append("`scratch-h4/cap8_gen.py`.")
L.append("-/")
L.append("")
L.append("namespace Kissing3D")
L.append("")
x, y, z = pts_str[7]
L.append("/-- The tetrahedral cap over the face `(pb0, pb1, pb5)`. -/")
L.append(f"noncomputable def pb7 : E3 := WithLp.toLp 2 ![{x}, {y}, {z}]")
L.append("")
L.append("/-- The capped pentagonal bipyramid: eight particles, eighteen bonds. -/")
L.append("noncomputable def capBipyr8 : Finset E3 := {pb0, pb1, pb2, pb3, pb4, pb5, pb6, pb7}")
L.append("")
L.append("section Cap8Distances")
L.append("")
L.append("private lemma hs5sq : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num)")
L.append("")
L.append("private lemma hr2sq : Real.sqrt 2 ^ 2 = 2 := Real.sq_sqrt (by norm_num)")
L.append("")
L.append("private lemma hs5le : Real.sqrt 5 ≤ 5 / 2 := by")
L.append("  nlinarith [hs5sq, Real.sqrt_nonneg 5]")
L.append("")
L.append("private lemma ht5sq : Real.sqrt (10 - 2 * Real.sqrt 5) ^ 2 = 10 - 2 * Real.sqrt 5 :=")
L.append("  Real.sq_sqrt (by linarith [hs5le])")
L.append("")
L.append("private lemma ne_of_dist_one' {a b : E3} (h : dist a b = 1) : a ≠ b := by")
L.append("  rintro rfl")
L.append("  rw [dist_self] at h")
L.append("  norm_num at h")
L.append("")
L.append("private lemma ne_of_dist_ge_one {a b : E3} (h : 1 ≤ dist a b) : a ≠ b := by")
L.append("  rintro rfl")
L.append("  rw [dist_self] at h")
L.append("  linarith")
L.append("")

vals = {s5: math.sqrt(5), t: math.sqrt(10-2*math.sqrt(5)), r2: math.sqrt(2)}

for (i, j) in BONDS:
    e = dist2(i, j)
    qs, r = redq(e - 1)
    assert r == 0, (i, j, r)
    se = show_expr(i, j)
    L.append(f"private lemma qd{i}{j} : dist pb{i} pb{j} = 1 := by")
    L.append("  rw [dist_coords]")
    L.append(f"  show Real.sqrt ({se}) = 1")
    L.append(f"  rw [show {se} = 1 by linear_combination {lc(qs)}]")
    L.append("  exact Real.sqrt_one")
    L.append("")

for (i, j) in NONBONDS:
    e = dist2(i, j)
    qs, target = redq(e)
    tstr = leanify(target)
    assert float(target.subs(vals)) >= 1.0
    se = show_expr(i, j)
    L.append(f"private lemma qge{i}{j} : 1 ≤ dist pb{i} pb{j} := by")
    L.append("  rw [dist_coords]")
    L.append(f"  show 1 ≤ Real.sqrt ({se})")
    L.append(f"  rw [show {se} = {tstr} by linear_combination {lc(qs)}]")
    L.append("  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]")
    L.append("  apply Real.sqrt_le_sqrt")
    L.append("  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,")
    L.append("    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,")
    L.append("    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]")
    L.append("")

ne_of = {}
for (i, j) in BONDS:
    ne_of[(i, j)] = f"ne_of_dist_one' qd{i}{j}"
for (i, j) in NONBONDS:
    ne_of[(i, j)] = f"ne_of_dist_ge_one qge{i}{j}"
for (i, j) in sorted(ne_of):
    L.append(f"private lemma qne{i}{j} : pb{i} ≠ pb{j} := {ne_of[(i,j)]}")
L.append("")
L.append("end Cap8Distances")
L.append("")
L.append("section Cap8Config")
L.append("")

def nes_from(i, rest):
    return ", ".join(f"qne{min(i,j)}{max(i,j)}" for j in rest)

L.append("private lemma cap8_dist : ∀ u ∈ capBipyr8, ∀ v ∈ capBipyr8, u ≠ v → 1 ≤ dist u v := by")
L.append("  have key : ∀ a b : E3, dist a b = 1 → 1 ≤ dist a b ∧ 1 ≤ dist b a := by")
L.append("    intro a b h")
L.append("    exact ⟨by rw [h], by rw [dist_comm, h]⟩")
L.append("  have key2 : ∀ a b : E3, 1 ≤ dist a b → 1 ≤ dist a b ∧ 1 ≤ dist b a := by")
L.append("    intro a b h")
L.append("    exact ⟨h, by rw [dist_comm]; exact h⟩")
L.append("  intro u hu v hv huv")
L.append("  simp only [capBipyr8, Finset.mem_insert, Finset.mem_singleton] at hu hv")
L.append("  rcases hu with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>")
L.append("    rcases hv with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>")
L.append("    first")
L.append("      | exact absurd rfl huv")
for (i, j) in BONDS:
    L.append(f"      | exact (key _ _ qd{i}{j}).1 | exact (key _ _ qd{i}{j}).2")
for (i, j) in NONBONDS:
    L.append(f"      | exact (key2 _ _ qge{i}{j}).1 | exact (key2 _ _ qge{i}{j}).2")
L.append("")
L.append("theorem hardCore_capBipyr8 : HardCore capBipyr8 := cap8_dist")
L.append("")
L.append("theorem card_capBipyr8 : capBipyr8.card = 8 := by")
L.append("  rw [capBipyr8]")
for k in range(7):
    rest = range(k + 1, 8)
    L.append(f"  rw [Finset.card_insert_of_notMem (by simp [{nes_from(k, rest)}])]")
L.append("  rw [Finset.card_singleton]")
L.append("")

NBRS = {0: [1, 4, 5, 6, 7], 1: [0, 2, 5, 6, 7], 2: [1, 3, 5, 6], 3: [2, 4, 5, 6],
        4: [0, 3, 5, 6], 5: [0, 1, 2, 3, 4, 7], 6: [0, 1, 2, 3, 4], 7: [0, 1, 5]}
for k in range(8):
    nb = NBRS[k]
    deg = len(nb)
    setstr = ", ".join(f"pb{j}" for j in nb)
    L.append(f"private lemma qdeg{k} : {deg} ≤ (neighbors capBipyr8 pb{k}).card := by")
    L.append(f"  have hsub : ({{{setstr}}} : Finset E3) ⊆ neighbors capBipyr8 pb{k} := by")
    L.append("    intro u hu")
    L.append("    simp only [Finset.mem_insert, Finset.mem_singleton] at hu")
    L.append("    rcases hu with " + " | ".join(["rfl"] * deg))
    for j in nb:
        name = f"qd{min(k,j)}{max(k,j)}"
        if k < j:
            L.append(f"    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], {name}⟩")
        else:
            L.append(f"    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact {name}⟩")
    L.append(f"  have hcard : ({{{setstr}}} : Finset E3).card = {deg} := by")
    for a in range(deg - 1):
        rest = nb[a + 1:]
        L.append(f"    rw [Finset.card_insert_of_notMem (by simp [{nes_from(nb[a], rest)}])]")
    L.append("    rw [Finset.card_singleton]")
    L.append("  calc " + str(deg) + f" = ({{{setstr}}} : Finset E3).card := hcard.symm")
    L.append("    _ ≤ _ := Finset.card_le_card hsub")
    L.append("")

L.append("/-- **Eight particles reach `E = −18`**: the capped pentagonal bipyramid carries")
L.append("36 ordered contacts. (The matching lower bound is the `E_min(8)` programme.) -/")
L.append("theorem energy_capBipyr8_le : energy capBipyr8 ≤ -18 := by")
L.append("  have hcc : 36 ≤ contactCount capBipyr8 := by")
L.append("    rw [contactCount, capBipyr8]")
for k in range(7):
    rest = range(k + 1, 8)
    L.append(f"    rw [Finset.sum_insert (by simp [{nes_from(k, rest)}])]")
L.append("    rw [Finset.sum_singleton]")
L.append("    simp only [show ({pb0, pb1, pb2, pb3, pb4, pb5, pb6, pb7} : Finset E3) = capBipyr8 from rfl]")
L.append("    have h0 := qdeg0; have h1 := qdeg1; have h2 := qdeg2; have h3 := qdeg3")
L.append("    have h4 := qdeg4; have h5 := qdeg5; have h6 := qdeg6; have h7 := qdeg7")
L.append("    omega")
L.append("  rw [energy]")
L.append("  have : (36 : ℝ) ≤ (contactCount capBipyr8 : ℝ) := by exact_mod_cast hcc")
L.append("  linarith")
L.append("")
L.append("end Cap8Config")
L.append("")
L.append("end Kissing3D")

open("/home/marek/Documents/Lean/physics/Physics/Cap8.lean", "w").write("\n".join(L) + "\n")

# numeric sanity
for (i, j) in BONDS:
    assert abs(float(dist2(i, j).subs(vals)) - 1) < 1e-12, (i, j)
for (i, j) in NONBONDS:
    assert float(dist2(i, j).subs(vals)) >= 1.0, (i, j)
print("wrote Physics/Cap8.lean; numeric checks pass")
