#!/usr/bin/env python3
"""Generate Physics/Cap9.lean: the doubly-capped pentagonal bipyramid (9 particles,
21 bonds) showing E_min(9) <= -21. Radicals: s5, t, r2 as in Cap8. The second cap
point pb8 sits under face (pb2, pb3, pb6), mirror-side from pb7's cap."""
import sympy as sp, math

s5, t, r2 = sp.symbols("s5 t r2", positive=True)
G = [r2**2 - 2, t**2 - (10 - 2*s5), s5**2 - 5]
S5, T, R2 = "Real.sqrt 5", "Real.sqrt (10 - 2 * Real.sqrt 5)", "Real.sqrt 2"

def redq(e):
    qs, r = sp.reduced(sp.expand(e), G, r2, t, s5, order='lex')
    while len(qs) < 3:
        qs.append(sp.Integer(0))
    return qs, sp.expand(r)

def leanify(e):
    s = sp.sstr(sp.nsimplify(e), full_prec=False)
    s = s.replace("**", "^").replace("s5", "@A@").replace("r2", "@C@").replace("t", "@B@")
    s = s.replace("@A@", f"({S5})").replace("@B@", f"({T})").replace("@C@", f"({R2})")
    return s

A = sp.Matrix([(5+s5)*t/20, 0, 0])
B = sp.Matrix([s5*t/20, (1+s5)/4, 0])
P2 = sp.Matrix([-(5+3*s5)*t/40, sp.Rational(1,2), 0])
P3 = sp.Matrix([-(5+3*s5)*t/40, sp.Rational(-1,2), 0])
P4 = sp.Matrix([s5*t/20, -(1+s5)/4, 0])
C5 = sp.Matrix([0, 0, s5*t/10])
C6 = sp.Matrix([0, 0, -s5*t/10])
n = (B-A).cross(C5-A)
n = sp.Matrix([redq(x)[1] for x in n])
P7 = (A+B+C5)/3 + sp.Rational(2,3)*r2*n
P7 = sp.Matrix([redq(x)[1] for x in P7])
n2 = (P3-P2).cross(C6-P2)
n2 = sp.Matrix([redq(x)[1] for x in n2])
P8 = (P2+P3+C6)/3 - sp.Rational(2,3)*r2*n2
P8 = sp.Matrix([redq(x)[1] for x in P8])
pts_sym = [A, B, P2, P3, P4, C5, C6, P7, P8]

BONDS = [(0,1),(1,2),(2,3),(3,4),(0,4),
         (0,5),(1,5),(2,5),(3,5),(4,5),
         (0,6),(1,6),(2,6),(3,6),(4,6),
         (0,7),(1,7),(5,7),
         (2,8),(3,8),(6,8)]
NONBONDS = [(0,2),(0,3),(1,3),(1,4),(2,4),(5,6),(2,7),(3,7),(4,7),(6,7),
            (0,8),(1,8),(4,8),(5,8),(7,8)]

def dist2(i, j):
    d = pts_sym[i] - pts_sym[j]
    return sp.expand(d.dot(d))

def lc(qs):
    terms = []
    for q, name in zip(qs, ["hr2sq", "ht5sq", "hs5sq"]):
        if q != 0:
            terms.append(f"({leanify(q)}) * {name}")
    return " + ".join(terms) if terms else "(0 : ℝ) * hs5sq"

pts_str = [
    (f"(5 + {S5}) * {T} / 20", "0", "0"),
    (f"{S5} * {T} / 20", f"(1 + {S5}) / 4", "0"),
    (f"-((5 + 3 * {S5}) * {T} / 40)", "1 / 2", "0"),
    (f"-((5 + 3 * {S5}) * {T} / 40)", "-(1 / 2)", "0"),
    (f"{S5} * {T} / 20", f"-((1 + {S5}) / 4)", "0"),
    ("0", "0", f"{S5} * {T} / 10"),
    ("0", "0", f"-({S5} * {T} / 10)"),
    tuple("0" if x == 0 else leanify(x) for x in pts_sym[7]),
    tuple("0" if x == 0 else leanify(x) for x in pts_sym[8]),
]

def show_expr(i, j):
    (xi, yi, zi), (xj, yj, zj) = pts_str[i], pts_str[j]
    return (f"(({xi} : ℝ) - ({xj}))^2 + (({yi} : ℝ) - ({yj}))^2 "
            f"+ (({zi} : ℝ) - ({zj}))^2")

L = []
L.append("import Physics.Cap8")
L.append("")
L.append("set_option linter.style.header false")
L.append("set_option maxHeartbeats 1600000")
L.append("")
L.append("/-!")
L.append("# `E_min(9) ≤ −21`: the doubly-capped pentagonal bipyramid")
L.append("")
L.append("Attach a ninth particle under the face `(pb2, pb3, pb6)` of the capped")
L.append("pentagonal bipyramid — a second regular-tetrahedron cap, edge-disjoint and")
L.append("mirror-side from the first. All 21 bonds are unit, the fifteen remaining pairs")
L.append("are `> 1` away, so the configuration is hard-core and carries 42 ordered")
L.append("contacts: `E ≤ −21` for nine particles. Machine-generated by")
L.append("`scratch-h4/cap9_gen.py`.")
L.append("-/")
L.append("")
L.append("namespace Kissing3D")
L.append("")
x, y, z = pts_str[8]
L.append("/-- The second tetrahedral cap, under the face `(pb2, pb3, pb6)`. -/")
L.append(f"noncomputable def pb8 : E3 := WithLp.toLp 2 ![{x}, {y}, {z}]")
L.append("")
L.append("/-- The doubly-capped pentagonal bipyramid: nine particles, 21 bonds. -/")
L.append("noncomputable def capBipyr9 : Finset E3 :=")
L.append("  {pb0, pb1, pb2, pb3, pb4, pb5, pb6, pb7, pb8}")
L.append("")
L.append("section Cap9Distances")
L.append("")
L.append("private lemma hs5sq : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num)")
L.append("")
L.append("private lemma hr2sq : Real.sqrt 2 ^ 2 = 2 := Real.sq_sqrt (by norm_num)")
L.append("")
L.append("private lemma hs5le : Real.sqrt 5 ≤ 5 / 2 := by")
L.append("  nlinarith [hs5sq, Real.sqrt_nonneg 5]")
L.append("")
L.append("private lemma ht5sq : Real.sqrt (10 - 2 * Real.sqrt 5) ^ 2 = 10 - 2 * Real.sqrt 5 :=")
L.append("  Real.sq_sqrt (by linarith [hs5le])")
L.append("")
L.append("private lemma ne_of_dist_one' {a b : E3} (h : dist a b = 1) : a ≠ b := by")
L.append("  rintro rfl")
L.append("  rw [dist_self] at h")
L.append("  norm_num at h")
L.append("")
L.append("private lemma ne_of_dist_ge_one {a b : E3} (h : 1 ≤ dist a b) : a ≠ b := by")
L.append("  rintro rfl")
L.append("  rw [dist_self] at h")
L.append("  linarith")
L.append("")

vals = {s5: math.sqrt(5), t: math.sqrt(10-2*math.sqrt(5)), r2: math.sqrt(2)}

for (i, j) in BONDS:
    e = dist2(i, j)
    qs, r = redq(e - 1)
    assert r == 0, (i, j, r)
    se = show_expr(i, j)
    L.append(f"private lemma qd{i}{j} : dist pb{i} pb{j} = 1 := by")
    L.append("  rw [dist_coords]")
    L.append(f"  show Real.sqrt ({se}) = 1")
    L.append(f"  rw [show {se} = 1 by linear_combination {lc(qs)}]")
    L.append("  exact Real.sqrt_one")
    L.append("")

for (i, j) in NONBONDS:
    e = dist2(i, j)
    qs, target = redq(e)
    tstr = leanify(target)
    assert float(target.subs(vals)) >= 1.0, (i, j, float(target.subs(vals)))
    se = show_expr(i, j)
    L.append(f"private lemma qge{i}{j} : 1 ≤ dist pb{i} pb{j} := by")
    L.append("  rw [dist_coords]")
    L.append(f"  show 1 ≤ Real.sqrt ({se})")
    L.append(f"  rw [show {se} = {tstr} by linear_combination {lc(qs)}]")
    L.append("  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]")
    L.append("  apply Real.sqrt_le_sqrt")
    L.append("  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,")
    L.append("    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq, ht5sq, hs5sq,")
    L.append("    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5),")
    L.append("    mul_nonneg (mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5))")
    L.append("      (Real.sqrt_nonneg (10 - 2 * Real.sqrt 5)),")
    L.append("    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg (10 - 2 * Real.sqrt 5)),")
    L.append("    mul_nonneg (Real.sqrt_nonneg 5) (Real.sqrt_nonneg (10 - 2 * Real.sqrt 5))]")
    L.append("")

ne_of = {}
for (i, j) in BONDS:
    ne_of[(i, j)] = f"ne_of_dist_one' qd{i}{j}"
for (i, j) in NONBONDS:
    ne_of[(i, j)] = f"ne_of_dist_ge_one qge{i}{j}"
for (i, j) in sorted(ne_of):
    L.append(f"private lemma qne{i}{j} : pb{i} ≠ pb{j} := {ne_of[(i,j)]}")
L.append("")
L.append("end Cap9Distances")
L.append("")
L.append("section Cap9Config")
L.append("")

def nes_from(i, rest):
    return ", ".join(f"qne{min(i,j)}{max(i,j)}" for j in rest)

ALLPTS = "{pb0, pb1, pb2, pb3, pb4, pb5, pb6, pb7, pb8}"
L.append("private lemma cap9_dist : ∀ u ∈ capBipyr9, ∀ v ∈ capBipyr9, u ≠ v → 1 ≤ dist u v := by")
L.append("  have key : ∀ a b : E3, dist a b = 1 → 1 ≤ dist a b ∧ 1 ≤ dist b a := by")
L.append("    intro a b h")
L.append("    exact ⟨by rw [h], by rw [dist_comm, h]⟩")
L.append("  have key2 : ∀ a b : E3, 1 ≤ dist a b → 1 ≤ dist a b ∧ 1 ≤ dist b a := by")
L.append("    intro a b h")
L.append("    exact ⟨h, by rw [dist_comm]; exact h⟩")
L.append("  intro u hu v hv huv")
L.append("  simp only [capBipyr9, Finset.mem_insert, Finset.mem_singleton] at hu hv")
L.append("  rcases hu with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>")
L.append("    rcases hv with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>")
L.append("    first")
L.append("      | exact absurd rfl huv")
for (i, j) in BONDS:
    L.append(f"      | exact (key _ _ qd{i}{j}).1 | exact (key _ _ qd{i}{j}).2")
for (i, j) in NONBONDS:
    L.append(f"      | exact (key2 _ _ qge{i}{j}).1 | exact (key2 _ _ qge{i}{j}).2")
L.append("")
L.append("theorem hardCore_capBipyr9 : HardCore capBipyr9 := cap9_dist")
L.append("")
L.append("theorem card_capBipyr9 : capBipyr9.card = 9 := by")
L.append("  rw [capBipyr9]")
for k in range(8):
    rest = range(k + 1, 9)
    L.append(f"  rw [Finset.card_insert_of_notMem (by simp [{nes_from(k, rest)}])]")
L.append("  rw [Finset.card_singleton]")
L.append("")

NBRS = {0: [1, 4, 5, 6, 7], 1: [0, 2, 5, 6, 7], 2: [1, 3, 5, 6, 8], 3: [2, 4, 5, 6, 8],
        4: [0, 3, 5, 6], 5: [0, 1, 2, 3, 4, 7], 6: [0, 1, 2, 3, 4, 8],
        7: [0, 1, 5], 8: [2, 3, 6]}
assert sum(len(v) for v in NBRS.values()) == 2 * len(BONDS)
for k, nb in NBRS.items():
    for j in nb:
        assert (min(k, j), max(k, j)) in BONDS

for k in range(9):
    nb = NBRS[k]
    deg = len(nb)
    setstr = ", ".join(f"pb{j}" for j in nb)
    L.append(f"private lemma qdeg{k} : {deg} ≤ (neighbors capBipyr9 pb{k}).card := by")
    L.append(f"  have hsub : ({{{setstr}}} : Finset E3) ⊆ neighbors capBipyr9 pb{k} := by")
    L.append("    intro u hu")
    L.append("    simp only [Finset.mem_insert, Finset.mem_singleton] at hu")
    L.append("    rcases hu with " + " | ".join(["rfl"] * deg))
    for j in nb:
        name = f"qd{min(k,j)}{max(k,j)}"
        if k < j:
            L.append(f"    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr9], {name}⟩")
        else:
            L.append(f"    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr9], by rw [dist_comm]; exact {name}⟩")
    L.append(f"  have hcard : ({{{setstr}}} : Finset E3).card = {deg} := by")
    for a in range(deg - 1):
        rest = nb[a + 1:]
        L.append(f"    rw [Finset.card_insert_of_notMem (by simp [{nes_from(nb[a], rest)}])]")
    L.append("    rw [Finset.card_singleton]")
    L.append("  calc " + str(deg) + f" = ({{{setstr}}} : Finset E3).card := hcard.symm")
    L.append("    _ ≤ _ := Finset.card_le_card hsub")
    L.append("")

L.append("/-- **Nine particles reach `E = −21`**: the doubly-capped pentagonal bipyramid")
L.append("carries 42 ordered contacts. (The matching lower bound is the `E_min(9)`")
L.append("programme.) -/")
L.append("theorem energy_capBipyr9_le : energy capBipyr9 ≤ -21 := by")
L.append("  have hcc : 42 ≤ contactCount capBipyr9 := by")
L.append("    rw [contactCount, capBipyr9]")
for k in range(8):
    rest = range(k + 1, 9)
    L.append(f"    rw [Finset.sum_insert (by simp [{nes_from(k, rest)}])]")
L.append("    rw [Finset.sum_singleton]")
L.append(f"    simp only [show ({ALLPTS} : Finset E3) = capBipyr9 from rfl]")
names = "; ".join(f"have h{k} := qdeg{k}" for k in range(9))
L.append(f"    {names}")
L.append("    omega")
L.append("  rw [energy]")
L.append("  have : (42 : ℝ) ≤ (contactCount capBipyr9 : ℝ) := by exact_mod_cast hcc")
L.append("  linarith")
L.append("")
L.append("end Cap9Config")
L.append("")
L.append("end Kissing3D")

open("/home/marek/Documents/Lean/physics/Physics/Cap9.lean", "w").write("\n".join(L) + "\n")

for (i, j) in BONDS:
    assert abs(float(dist2(i, j).subs(vals)) - 1) < 1e-12, (i, j)
for (i, j) in NONBONDS:
    v = float(dist2(i, j).subs(vals))
    assert v >= 1.0, (i, j, v)
    print(f"nonbond ({i},{j}): dist = {math.sqrt(v):.6f}")
print("wrote Physics/Cap9.lean; numeric checks pass")
