#!/usr/bin/env python3
"""Generate Physics/Emin9.lean: the E_min(9) assembly layer.

Ports the Emin8 walk/codec architecture to 36 pairs over Fin 9 (base-16
certificate fields) and generates checkCert + checkCert_sound cases for a
configurable pattern list:
  kinds 0-9 : cheap kills (as Emin8, with N=9 constants)
  kind 10   : P6  (pattern_p6_impossible, 6 labels)
  kinds 11+ : obs patterns (pattern_obs{k}_impossible, 7 labels)
  kinds ... : class patterns (pattern_class{c}_impossible, 9 labels)
Patterns use the UNIFORM new-style signature:
  (hX) {q : Fin n → E3} (hq) (hinj) (bond hyps in sorted edge order) : False
"""
import sys, pickle, itertools

# ---------------- pattern list ----------------
P6E = [(0,1),(0,2),(0,3),(0,4),(1,2),(1,3),(1,5),(2,3),(2,5),(3,5),(4,5)]
d = pickle.load(open('scratch-h4/emin9_subpat.pkl', 'rb'))
OBS_IDXS = [7, 3, 0]          # proven obs lemmas (must be compiled)
CLASS_IDXS = []               # filled in as class certificates land
try:
    CLASS_IDXS = pickle.load(open('scratch-h4/emin9_proven_classes.pkl', 'rb'))
except FileNotFoundError:
    pass
nc = pickle.load(open('scratch-h4/emin9_newclasses.pkl', 'rb'))

PATTERNS = []   # (kind, lean_lemma, nlabels, sorted_edge_list)
PATTERNS.append((10, 'pattern_p6_impossible', 6, sorted(P6E)))
kind = 11
for k in OBS_IDXS:
    E = sorted(d['obstructions'][k][0])
    PATTERNS.append((kind, f'pattern_obs{k}_impossible', 7, E))
    kind += 1
CLASS_IDXS = sorted(set(CLASS_IDXS) | {23})
for c in CLASS_IDXS:
    ns = set(nc[c][2])
    E = sorted(p for p in itertools.combinations(range(9), 2) if p not in ns)
    PATTERNS.append((kind, f'pattern_class{c}_impossible', 9, E))
    kind += 1
try:
    P8_PROVEN = pickle.load(open('scratch-h4/emin9_proven_p8.pkl', 'rb'))
except FileNotFoundError:
    P8_PROVEN = []
if P8_PROVEN:
    pats8 = pickle.load(open('scratch-h4/emin9_pat8.pkl', 'rb'))
    for pk in P8_PROVEN:
        E8 = sorted(tuple(e) for e in pats8[pk][0])
        PATTERNS.append((kind, f'pattern_q{pk}_impossible', 8, E8))
        kind += 1
NKINDS = kind
print(f'patterns: {[(kk, nm, len(E)) for kk, nm, nl, E in PATTERNS]}')

L = []
def em(s=''):
    L.append(s)

em('import Physics.Emin8Final')
em('import Physics.Emin9Kills')
em('import Physics.Emin9Canon')
for k in OBS_IDXS:
    em(f'import Physics.Emin9P{k}')
for c in CLASS_IDXS:
    em(f'import Physics.Emin9C{c}')
for pk in P8_PROVEN:
    em(f'import Physics.Emin9Q{pk}')
em()
em('set_option linter.style.header false')
em('set_option linter.unusedSimpArgs false')
em('set_option maxHeartbeats 4000000')
em('set_option maxRecDepth 200000')
em()
em('/-!')
em('# Towards `E_min(9) = −21`: the assembly layer')
em()
em('Machine-generated by `scratch-h4/emin9_gen.py`, porting the `Emin8` walk')
em('architecture to the 36 pair decisions of `Fin 9` with base-16 certificate')
em('fields, and adding the new geometric kill patterns (P6, SOS obstruction')
em('lemmas, and full survivor-class certificates).')
em('-/')
em()
em('namespace Kissing3D')
em()
em('open Finset')
em()
em('open scoped Classical in')
em('/-- **Minimum degree four** for nine particles: at `43` or more ordered contacts,')
em('deleting a degree-`≤3` particle would leave eight particles with `≥ 37` ordered')
em('contacts, contradicting `eight_particle_bound`. -/')
em('theorem degree_ge_four_9 {X : Finset E3} (hX : HardCore X) (h9 : X.card = 9)')
em('    (hcc : 43 ≤ contactCount X) : ∀ v ∈ X, 4 ≤ (neighbors X v).card := by')
em('  intro v hv')
em('  by_contra hlt')
em('  push_neg at hlt')
em('  have herase := contactCount_erase (X := X) (v := v) hv')
em('  have hY : (X.erase v).card = 8 := by rw [Finset.card_erase_of_mem hv, h9]')
em('  have hXY : HardCore (X.erase v) := fun a ha b hb hab =>')
em('    hX a (Finset.mem_of_mem_erase ha) b (Finset.mem_of_mem_erase hb) hab')
em('  have hbound := eight_particle_bound hXY hY')
em('  omega')
em()
em('namespace Emin9T')
em()

em('/-- Index of the pair `{i, j}` (for `i < j < 9`) in incremental order. -/')
em('def pairIdx9 (i j : ℕ) : ℕ :=')
em('  let a := min i j')
em('  let b := max i j')
em('  b * (b - 1) / 2 + a')
em()
em('/-- Bond test against the decided edge list. -/')
em('def eMem (es : List ℕ) (i j : ℕ) : Bool :=')
em('  decide (i < 9) && decide (j < 9) && (i != j) && es.contains (pairIdx9 i j)')
em()
em('/-- Base-16 payload field `k` of a packed certificate (after the base-64 kind digit). -/')
em('def fld (cert k : ℕ) : ℕ := cert / (64 * 16 ^ k) % 16')
em()

# ---------------- checkCert ----------------
em('/-- Certificate check against the decided edge and non-edge index lists. -/')
em('def checkCert (es ns : List ℕ) (cert : ℕ) : Bool :=')
em('  let kind := cert % 64')
em('  if kind == 0 then')
em('    let v := fld cert 0')
em('    decide (v < 9) &&')
em('      decide (5 ≤ (ns.filter (fun k => (pairFst k == v) || (pairSnd k == v))).length)')
em('  else if kind == 1 then')
em('    decide (15 ≤ ns.length)')
em('  else if kind == 2 then')
em('    let a := fld cert 0; let b := fld cert 1; let c := fld cert 2')
em('    let d := fld cert 3; let e := fld cert 4')
em('    eMem es a b && eMem es a c && eMem es a d && eMem es a e &&')
em('    eMem es b c && eMem es b d && eMem es b e &&')
em('    eMem es c d && eMem es c e && eMem es d e')
em('  else if kind == 3 then')
em('    let u := fld cert 0; let v := fld cert 1; let c := fld cert 2')
em('    let x := fld cert 3; let y := fld cert 4; let z := fld cert 5')
em('    eMem es u v && eMem es u c && eMem es v c && eMem es u x && eMem es v x &&')
em('    eMem es u y && eMem es v y && eMem es u z && eMem es v z &&')
em('    eMem es c x && eMem es c y && eMem es c z &&')
em('    (x != y) && (x != z) && (y != z)')
em('  else if kind == 4 then')
em('    let u := fld cert 0; let v := fld cert 1')
em('    let w1 := fld cert 2; let w2 := fld cert 3; let w3 := fld cert 4')
em('    let w4 := fld cert 5; let w5 := fld cert 6; let w6 := fld cert 7')
em('    eMem es u v &&')
em('    eMem es u w1 && eMem es v w1 && eMem es u w2 && eMem es v w2 &&')
em('    eMem es u w3 && eMem es v w3 && eMem es u w4 && eMem es v w4 &&')
em('    eMem es u w5 && eMem es v w5 && eMem es u w6 && eMem es v w6 &&')
em('    (w1 != w2) && (w1 != w3) && (w1 != w4) && (w1 != w5) && (w1 != w6) &&')
em('    (w2 != w3) && (w2 != w4) && (w2 != w5) && (w2 != w6) &&')
em('    (w3 != w4) && (w3 != w5) && (w3 != w6) &&')
em('    (w4 != w5) && (w4 != w6) && (w5 != w6)')
em('  else if kind == 5 then')
em('    let a := fld cert 0; let b := fld cert 1; let c := fld cert 2')
em('    let w1 := fld cert 3; let w2 := fld cert 4; let w3 := fld cert 5')
em('    (a != b) && (a != c) && (b != c) &&')
em('    (w1 != w2) && (w1 != w3) && (w2 != w3) &&')
em('    eMem es a w1 && eMem es b w1 && eMem es c w1 &&')
em('    eMem es a w2 && eMem es b w2 && eMem es c w2 &&')
em('    eMem es a w3 && eMem es b w3 && eMem es c w3')
# P1/P4/P5 (kinds 6-8), Emin8 edge lists with 7 labels
P1L = [(0,3),(0,4),(0,5),(1,2),(1,4),(1,5),(2,3),(2,4),(3,4),
       (0,6),(1,6),(2,6),(3,6),(4,6),(5,6)]
P4L = [(0,1),(0,4),(0,5),(1,2),(1,3),(2,3),(2,5),(3,4),(4,5),
       (0,6),(1,6),(2,6),(3,6),(4,6),(5,6)]
P5L = [(0,3),(0,4),(0,5),(1,2),(1,4),(1,5),(2,3),(2,5),(3,4),
       (1,6),(2,6),(3,6),(4,6),(5,6)]
for kd, pe in ((6, P1L), (7, P4L), (8, P5L)):
    em(f'  else if kind == {kd} then')
    em('    let m := fun t => fld cert t')
    em('    (List.range 7).all (fun t => decide (m t < 9)) &&')
    em("    ((List.range 7).all fun t => ((List.range t).all fun t' => m t != m t')) &&")
    conj = ' &&\n'.join(
        '    ' + ' && '.join(f'eMem es (m {a}) (m {b})' for a, b in pe[r:r+3])
        for r in range(0, len(pe), 3))
    em(conj)
em('  else if kind == 9 then')
em('    -- canonicity: permutation m whose determined image dominates the prefix at i')
em('    let m := fun t => fld cert t')
em('    let i := fld cert 9 + 16 * fld cert 10')
em('    (List.range 9).all (fun t => decide (m t < 9)) &&')
em("    ((List.range 9).all fun t => ((List.range t).all fun t' => m t != m t')) &&")
em('    decide (i < 36) &&')
em('    ((List.range i).all fun j =>')
em('      ((es.contains j && es.contains (pairIdx9 (m (pairFst j)) (m (pairSnd j)))) ||')
em('       (ns.contains j && ns.contains (pairIdx9 (m (pairFst j)) (m (pairSnd j)))))) &&')
em('    ns.contains i &&')
em('    es.contains (pairIdx9 (m (pairFst i)) (m (pairSnd i)))')
for kd, name, nl, pe in PATTERNS:
    em(f'  else if kind == {kd} then')
    em('    let m := fun t => fld cert t')
    em(f'    (List.range {nl}).all (fun t => decide (m t < 9)) &&')
    em(f"    ((List.range {nl}).all fun t => ((List.range t).all fun t' => m t != m t')) &&")
    conj = ' &&\n'.join(
        '    ' + ' && '.join(f'eMem es (m {a}) (m {b})' for a, b in pe[r:r+3])
        for r in range(0, len(pe), 3))
    em(conj)
em('  else false')
em()

# ---------------- walk ----------------
em('/-- Walk the serialized tree: `0` = branch on pair `k`, odd = kill leaf. -/')
em('def walk : ℕ → List ℕ → ℕ → List ℕ → List ℕ → Option (List ℕ)')
em('  | 0, _, _, _, _ => none')
em('  | _, [], _, _, _ => none')
em('  | fuel + 1, c :: rest, k, es, ns =>')
em('    if c == 0 then')
em('      if k < 36 then')
em('        match walk fuel rest (k + 1) (k :: es) ns with')
em('        | none => none')
em('        | some rest2 => walk fuel rest2 (k + 1) es (k :: ns)')
em('      else none')
em('    else if checkCert es ns ((c - 1) / 2) then some rest else none')
em()
em('/-- Composition: a sub-walk returning remainder `r` extends over an appended tail. -/')
em('lemma walk_append {fuel : ℕ} {l1 l2 r : List ℕ} {k : ℕ} {es ns : List ℕ}')
em('    (h : walk fuel l1 k es ns = some r) :')
em('    walk fuel (l1 ++ l2) k es ns = some (r ++ l2) := by')
em('  induction fuel generalizing l1 r k es ns with')
em('  | zero => simp [walk] at h')
em('  | succ fuel ih =>')
em('    match l1 with')
em('    | [] => simp [walk] at h')
em('    | c :: rest =>')
em('      rw [List.cons_append]')
em('      rw [show walk (fuel + 1) (c :: rest) k es ns')
em('          = (if c == 0 then')
em('              if k < 36 then')
em('                match walk fuel rest (k + 1) (k :: es) ns with')
em('                | none => none')
em('                | some rest2 => walk fuel rest2 (k + 1) es (k :: ns)')
em('              else none')
em('            else if checkCert es ns ((c - 1) / 2) then some rest else none) from rfl] at h')
em('      rw [show walk (fuel + 1) ((c :: (rest ++ l2))) k es ns')
em('          = (if c == 0 then')
em('              if k < 36 then')
em('                match walk fuel (rest ++ l2) (k + 1) (k :: es) ns with')
em('                | none => none')
em('                | some rest2 => walk fuel rest2 (k + 1) es (k :: ns)')
em('              else none')
em('            else if checkCert es ns ((c - 1) / 2) then some (rest ++ l2)')
em('            else none) from rfl]')
em('      by_cases hc : c == 0')
em('      · rw [if_pos hc] at h ⊢')
em('        by_cases hk : k < 36')
em('        · rw [if_pos hk] at h ⊢')
em('          cases hw : walk fuel rest (k + 1) (k :: es) ns with')
em('          | none => rw [hw] at h; simp at h')
em('          | some rest2 =>')
em('            rw [hw] at h')
em('            simp only at h')
em('            rw [ih hw]')
em('            simp only')
em('            exact ih h')
em('        · rw [if_neg hk] at h')
em('          exact absurd h (by simp)')
em('      · rw [if_neg hc] at h ⊢')
em('        by_cases hcc : checkCert es ns ((c - 1) / 2)')
em('        · rw [if_pos hcc] at h ⊢')
em('          simp only [Option.some.injEq] at h')
em('          rw [h]')
em('        · rw [if_neg hcc] at h')
em('          exact absurd h (by simp)')
em()
em('/-- Codec facts, kernel-checked. -/')
em('lemma pair_codec : ∀ i < 9, ∀ j < 9, i ≠ j →')
em('    pairIdx9 i j < 36 ∧ pairFst (pairIdx9 i j) = min i j ∧')
em('      pairSnd (pairIdx9 i j) = max i j := by decide')
em()
em("lemma pair_decode_inj : ∀ i < 36, ∀ i' < 36,")
em("    pairFst i = pairFst i' → pairSnd i = pairSnd i' → i = i' := by decide")
em()
em('lemma pair_decode_lt : ∀ i < 36, pairFst i < pairSnd i ∧ pairSnd i < 9 := by decide')
em()

_txt = '\n'.join(L) + '\n'
_txt = _txt.replace('pairFst', 'cPairFst').replace('pairSnd', 'cPairSnd')
open('/home/marek/Documents/Lean/physics/scratch-h4/emin9_gen_part1.txt', 'w').write(_txt)
print('part 1 written:', len(L), 'lines')
