import ContactNumbers.Bipyramid7

set_option linter.style.header false
set_option maxHeartbeats 1000000

/-!
# `E_min(8) ≤ −18`: the capped pentagonal bipyramid

Attach an eighth particle over the face `(pb0, pb1, pb5)` of the unit-edge
pentagonal bipyramid — a regular tetrahedron cap. All 18 bonds are unit, the ten
remaining pairs are `≥ √(4/3)` away, so the configuration is hard-core and carries
36 ordered contacts: `E ≤ −18` for eight particles. Machine-generated by
`scratch-h4/cap8_gen.py`.
-/

namespace Kissing3D

/-- The tetrahedral cap over the face `(pb0, pb1, pb5)`. -/
noncomputable def pb7 : E3 := WithLp.toLp 2 ![(Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12, (Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12, (Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30]

/-- The capped pentagonal bipyramid: eight particles, eighteen bonds. -/
noncomputable def capBipyr8 : Finset E3 := {pb0, pb1, pb2, pb3, pb4, pb5, pb6, pb7}

section Cap8Distances

private lemma hs5sq : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num)

private lemma hr2sq : Real.sqrt 2 ^ 2 = 2 := Real.sq_sqrt (by norm_num)

private lemma hs5le : Real.sqrt 5 ≤ 5 / 2 := by
  nlinarith [hs5sq, Real.sqrt_nonneg 5]

private lemma ht5sq : Real.sqrt (10 - 2 * Real.sqrt 5) ^ 2 = 10 - 2 * Real.sqrt 5 :=
  Real.sq_sqrt (by linarith [hs5le])

private lemma ne_of_dist_one' {a b : E3} (h : dist a b = 1) : a ≠ b := by
  rintro rfl
  rw [dist_self] at h
  norm_num at h

private lemma ne_of_dist_ge_one {a b : E3} (h : 1 ≤ dist a b) : a ≠ b := by
  rintro rfl
  rw [dist_self] at h
  linarith

private lemma qd01 : dist pb0 pb1 = 1 := by
  rw [dist_coords]
  show Real.sqrt ((((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + ((0 : ℝ) - ((1 + Real.sqrt 5) / 4))^2 + ((0 : ℝ) - (0))^2) = 1
  rw [show (((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + ((0 : ℝ) - ((1 + Real.sqrt 5) / 4))^2 + ((0 : ℝ) - (0))^2 = 1 by linear_combination (1/16) * ht5sq + (1/16) * hs5sq]
  exact Real.sqrt_one

private lemma qd12 : dist pb1 pb2 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (1 / 2))^2 + ((0 : ℝ) - (0))^2) = 1
  rw [show ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (1 / 2))^2 + ((0 : ℝ) - (0))^2 = 1 by linear_combination ((Real.sqrt 5)^2/64 + (Real.sqrt 5)/32 + 1/64) * ht5sq + (5/32 - (Real.sqrt 5)/32) * hs5sq]
  exact Real.sqrt_one

private lemma qd23 : dist pb2 pb3 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + ((1 / 2 : ℝ) - (-(1 / 2)))^2 + ((0 : ℝ) - (0))^2) = 1
  rw [show ((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + ((1 / 2 : ℝ) - (-(1 / 2)))^2 + ((0 : ℝ) - (0))^2 = 1 by linear_combination (0 : ℝ) * hs5sq]
  exact Real.sqrt_one

private lemma qd34 : dist pb3 pb4 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + ((-(1 / 2) : ℝ) - (-((1 + Real.sqrt 5) / 4)))^2 + ((0 : ℝ) - (0))^2) = 1
  rw [show ((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + ((-(1 / 2) : ℝ) - (-((1 + Real.sqrt 5) / 4)))^2 + ((0 : ℝ) - (0))^2 = 1 by linear_combination ((Real.sqrt 5)^2/64 + (Real.sqrt 5)/32 + 1/64) * ht5sq + (5/32 - (Real.sqrt 5)/32) * hs5sq]
  exact Real.sqrt_one

private lemma qd04 : dist pb0 pb4 = 1 := by
  rw [dist_coords]
  show Real.sqrt ((((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + ((0 : ℝ) - (-((1 + Real.sqrt 5) / 4)))^2 + ((0 : ℝ) - (0))^2) = 1
  rw [show (((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + ((0 : ℝ) - (-((1 + Real.sqrt 5) / 4)))^2 + ((0 : ℝ) - (0))^2 = 1 by linear_combination (1/16) * ht5sq + (1/16) * hs5sq]
  exact Real.sqrt_one

private lemma qd05 : dist pb0 pb5 = 1 := by
  rw [dist_coords]
  show Real.sqrt ((((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + ((0 : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2) = 1
  rw [show (((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + ((0 : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2 = 1 by linear_combination ((Real.sqrt 5)^2/80 + (Real.sqrt 5)/40 + 1/16) * ht5sq + (3/40 - (Real.sqrt 5)/40) * hs5sq]
  exact Real.sqrt_one

private lemma qd15 : dist pb1 pb5 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2) = 1
  rw [show ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2 = 1 by linear_combination ((Real.sqrt 5)^2/80) * ht5sq + (3/16 - (Real.sqrt 5)/40) * hs5sq]
  exact Real.sqrt_one

private lemma qd25 : dist pb2 pb5 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (0))^2 + ((1 / 2 : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2) = 1
  rw [show ((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (0))^2 + ((1 / 2 : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2 = 1 by linear_combination ((Real.sqrt 5)^2/64 + 3*(Real.sqrt 5)/160 + 1/64) * ht5sq + (19/160 - (Real.sqrt 5)/32) * hs5sq]
  exact Real.sqrt_one

private lemma qd35 : dist pb3 pb5 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (0))^2 + ((-(1 / 2) : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2) = 1
  rw [show ((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (0))^2 + ((-(1 / 2) : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2 = 1 by linear_combination ((Real.sqrt 5)^2/64 + 3*(Real.sqrt 5)/160 + 1/64) * ht5sq + (19/160 - (Real.sqrt 5)/32) * hs5sq]
  exact Real.sqrt_one

private lemma qd45 : dist pb4 pb5 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + ((-((1 + Real.sqrt 5) / 4) : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2) = 1
  rw [show ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + ((-((1 + Real.sqrt 5) / 4) : ℝ) - (0))^2 + ((0 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10))^2 = 1 by linear_combination ((Real.sqrt 5)^2/80) * ht5sq + (3/16 - (Real.sqrt 5)/40) * hs5sq]
  exact Real.sqrt_one

private lemma qd06 : dist pb0 pb6 = 1 := by
  rw [dist_coords]
  show Real.sqrt ((((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + ((0 : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2) = 1
  rw [show (((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + ((0 : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2 = 1 by linear_combination ((Real.sqrt 5)^2/80 + (Real.sqrt 5)/40 + 1/16) * ht5sq + (3/40 - (Real.sqrt 5)/40) * hs5sq]
  exact Real.sqrt_one

private lemma qd16 : dist pb1 pb6 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2) = 1
  rw [show ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2 = 1 by linear_combination ((Real.sqrt 5)^2/80) * ht5sq + (3/16 - (Real.sqrt 5)/40) * hs5sq]
  exact Real.sqrt_one

private lemma qd26 : dist pb2 pb6 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (0))^2 + ((1 / 2 : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2) = 1
  rw [show ((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (0))^2 + ((1 / 2 : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2 = 1 by linear_combination ((Real.sqrt 5)^2/64 + 3*(Real.sqrt 5)/160 + 1/64) * ht5sq + (19/160 - (Real.sqrt 5)/32) * hs5sq]
  exact Real.sqrt_one

private lemma qd36 : dist pb3 pb6 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (0))^2 + ((-(1 / 2) : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2) = 1
  rw [show ((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (0))^2 + ((-(1 / 2) : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2 = 1 by linear_combination ((Real.sqrt 5)^2/64 + 3*(Real.sqrt 5)/160 + 1/64) * ht5sq + (19/160 - (Real.sqrt 5)/32) * hs5sq]
  exact Real.sqrt_one

private lemma qd46 : dist pb4 pb6 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + ((-((1 + Real.sqrt 5) / 4) : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2) = 1
  rw [show ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (0))^2 + ((-((1 + Real.sqrt 5) / 4) : ℝ) - (0))^2 + ((0 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2 = 1 by linear_combination ((Real.sqrt 5)^2/80) * ht5sq + (3/16 - (Real.sqrt 5)/40) * hs5sq]
  exact Real.sqrt_one

private lemma qd07 : dist pb0 pb7 = 1 := by
  rw [dist_coords]
  show Real.sqrt ((((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2) = 1
  rw [show (((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2 = 1 by linear_combination ((Real.sqrt 5)^2*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/360 + (Real.sqrt 5)^2/36 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/90 - (Real.sqrt 5)/18 + (Real.sqrt (10 - 2 * Real.sqrt 5))^2/72 + 1/36) * hr2sq + ((Real.sqrt 2)*(Real.sqrt 5)^2/360 - (Real.sqrt 2)*(Real.sqrt 5)/360 - (Real.sqrt 2)/36 + (Real.sqrt 5)^2/144 + (Real.sqrt 5)/36 + 1/18) * ht5sq + (-(Real.sqrt 2)*(Real.sqrt 5)/180 + 11*(Real.sqrt 2)/180 - (Real.sqrt 5)/72 + 11/144) * hs5sq]
  exact Real.sqrt_one

private lemma qd17 : dist pb1 pb7 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2) = 1
  rw [show ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2 = 1 by linear_combination ((Real.sqrt 5)^2*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/360 + (Real.sqrt 5)^2/36 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/90 - (Real.sqrt 5)/18 + (Real.sqrt (10 - 2 * Real.sqrt 5))^2/72 + 1/36) * hr2sq + ((Real.sqrt 2)*(Real.sqrt 5)^2/360 + (Real.sqrt 2)*(Real.sqrt 5)/180 + (Real.sqrt 2)/72 + (Real.sqrt 5)^2/144 + 7*(Real.sqrt 5)/360 + 5/144) * ht5sq + (-(Real.sqrt 2)*(Real.sqrt 5)/180 - 7*(Real.sqrt 2)/180 - (Real.sqrt 5)/72 + 41/360) * hs5sq]
  exact Real.sqrt_one

private lemma qd57 : dist pb5 pb7 = 1 := by
  rw [dist_coords]
  show Real.sqrt (((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2) = 1
  rw [show ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2 = 1 by linear_combination ((Real.sqrt 5)^2*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/360 + (Real.sqrt 5)^2/36 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/90 - (Real.sqrt 5)/18 + (Real.sqrt (10 - 2 * Real.sqrt 5))^2/72 + 1/36) * hr2sq + (-(Real.sqrt 2)*(Real.sqrt 5)^2/180 - (Real.sqrt 2)*(Real.sqrt 5)/360 + (Real.sqrt 2)/72 + (Real.sqrt 5)^2/90 + (Real.sqrt 5)/36 + 5/144) * ht5sq + ((Real.sqrt 2)*(Real.sqrt 5)/90 - (Real.sqrt 2)/45 - (Real.sqrt 5)/45 + 17/144) * hs5sq]
  exact Real.sqrt_one

private lemma qge02 : 1 ≤ dist pb0 pb2 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt ((((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + ((0 : ℝ) - (1 / 2))^2 + ((0 : ℝ) - (0))^2)
  rw [show (((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + ((0 : ℝ) - (1 / 2))^2 + ((0 : ℝ) - (0))^2 = (Real.sqrt 5)/2 + 3/2 by linear_combination ((Real.sqrt 5)^2/64 + 3*(Real.sqrt 5)/32 + 9/64) * ht5sq + (-(Real.sqrt 5)/32 - 1/32) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qge03 : 1 ≤ dist pb0 pb3 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt ((((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + ((0 : ℝ) - (-(1 / 2)))^2 + ((0 : ℝ) - (0))^2)
  rw [show (((5 + Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + ((0 : ℝ) - (-(1 / 2)))^2 + ((0 : ℝ) - (0))^2 = (Real.sqrt 5)/2 + 3/2 by linear_combination ((Real.sqrt 5)^2/64 + 3*(Real.sqrt 5)/32 + 9/64) * ht5sq + (-(Real.sqrt 5)/32 - 1/32) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qge13 : 1 ≤ dist pb1 pb3 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt (((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (-(1 / 2)))^2 + ((0 : ℝ) - (0))^2)
  rw [show ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40)))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (-(1 / 2)))^2 + ((0 : ℝ) - (0))^2 = (Real.sqrt 5)/2 + 3/2 by linear_combination ((Real.sqrt 5)^2/64 + (Real.sqrt 5)/32 + 1/64) * ht5sq + (5/32 - (Real.sqrt 5)/32) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qge14 : 1 ≤ dist pb1 pb4 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt (((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (-((1 + Real.sqrt 5) / 4)))^2 + ((0 : ℝ) - (0))^2)
  rw [show ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + (((1 + Real.sqrt 5) / 4 : ℝ) - (-((1 + Real.sqrt 5) / 4)))^2 + ((0 : ℝ) - (0))^2 = (Real.sqrt 5)/2 + 3/2 by linear_combination (1/4) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qge24 : 1 ≤ dist pb2 pb4 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt (((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + ((1 / 2 : ℝ) - (-((1 + Real.sqrt 5) / 4)))^2 + ((0 : ℝ) - (0))^2)
  rw [show ((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - (Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20))^2 + ((1 / 2 : ℝ) - (-((1 + Real.sqrt 5) / 4)))^2 + ((0 : ℝ) - (0))^2 = (Real.sqrt 5)/2 + 3/2 by linear_combination ((Real.sqrt 5)^2/64 + (Real.sqrt 5)/32 + 1/64) * ht5sq + (5/32 - (Real.sqrt 5)/32) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qge56 : 1 ≤ dist pb5 pb6 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt (((0 : ℝ) - (0))^2 + ((0 : ℝ) - (0))^2 + ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2)
  rw [show ((0 : ℝ) - (0))^2 + ((0 : ℝ) - (0))^2 + ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10 : ℝ) - (-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10)))^2 = 2 - 2*(Real.sqrt 5)/5 by linear_combination ((Real.sqrt 5)^2/25) * ht5sq + (2/5 - 2*(Real.sqrt 5)/25) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qge27 : 1 ≤ dist pb2 pb7 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt (((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((1 / 2 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2)
  rw [show ((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((1 / 2 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2 = 2*(Real.sqrt 2)/3 + (Real.sqrt 5)/6 + 3/2 by linear_combination ((Real.sqrt 5)^2*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/360 + (Real.sqrt 5)^2/36 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/90 - (Real.sqrt 5)/18 + (Real.sqrt (10 - 2 * Real.sqrt 5))^2/72 + 1/36) * hr2sq + ((Real.sqrt 2)*(Real.sqrt 5)^2/144 + 11*(Real.sqrt 2)*(Real.sqrt 5)/360 + 5*(Real.sqrt 2)/144 + 53*(Real.sqrt 5)^2/2880 + 97*(Real.sqrt 5)/1440 + 41/576) * ht5sq + (-(Real.sqrt 2)*(Real.sqrt 5)/72 + 13*(Real.sqrt 2)/360 - 53*(Real.sqrt 5)/1440 + 161/1440) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qge37 : 1 ≤ dist pb3 pb7 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt (((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((-(1 / 2) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2)
  rw [show ((-((5 + 3 * Real.sqrt 5) * Real.sqrt (10 - 2 * Real.sqrt 5) / 40) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((-(1 / 2) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2 = (Real.sqrt 2)*(Real.sqrt 5)/3 + (Real.sqrt 2)/3 + (Real.sqrt 5)/3 + 5/3 by linear_combination ((Real.sqrt 5)^2*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/360 + (Real.sqrt 5)^2/36 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/90 - (Real.sqrt 5)/18 + (Real.sqrt (10 - 2 * Real.sqrt 5))^2/72 + 1/36) * hr2sq + ((Real.sqrt 2)*(Real.sqrt 5)^2/144 + 11*(Real.sqrt 2)*(Real.sqrt 5)/360 + 5*(Real.sqrt 2)/144 + 53*(Real.sqrt 5)^2/2880 + 97*(Real.sqrt 5)/1440 + 41/576) * ht5sq + (-(Real.sqrt 2)*(Real.sqrt 5)/72 + 13*(Real.sqrt 2)/360 - 53*(Real.sqrt 5)/1440 + 161/1440) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qge47 : 1 ≤ dist pb4 pb7 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt (((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((-((1 + Real.sqrt 5) / 4) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2)
  rw [show ((Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 20 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((-((1 + Real.sqrt 5) / 4) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2 = 2*(Real.sqrt 2)/3 + (Real.sqrt 5)/6 + 3/2 by linear_combination ((Real.sqrt 5)^2*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/360 + (Real.sqrt 5)^2/36 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/90 - (Real.sqrt 5)/18 + (Real.sqrt (10 - 2 * Real.sqrt 5))^2/72 + 1/36) * hr2sq + ((Real.sqrt 2)*(Real.sqrt 5)^2/360 + (Real.sqrt 2)*(Real.sqrt 5)/180 + (Real.sqrt 2)/72 + (Real.sqrt 5)^2/144 + 7*(Real.sqrt 5)/360 + 5/144) * ht5sq + (-(Real.sqrt 2)*(Real.sqrt 5)/180 + 23*(Real.sqrt 2)/180 - (Real.sqrt 5)/72 + 71/360) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qge67 : 1 ≤ dist pb6 pb7 := by
  rw [dist_coords]
  show 1 ≤ Real.sqrt (((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2)
  rw [show ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/60 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30 + (Real.sqrt (10 - 2 * Real.sqrt 5))/12))^2 + ((0 : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)/6 - (Real.sqrt 2)/6 + (Real.sqrt 5)/12 + 1/12))^2 + ((-(Real.sqrt 5 * Real.sqrt (10 - 2 * Real.sqrt 5) / 10) : ℝ) - ((Real.sqrt 2)*(Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/20 + (Real.sqrt 2)*(Real.sqrt (10 - 2 * Real.sqrt 5))/12 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))/30))^2 = 2*(Real.sqrt 2)*(Real.sqrt 5)/15 + 2*(Real.sqrt 2)/3 - 2*(Real.sqrt 5)/15 + 5/3 by linear_combination ((Real.sqrt 5)^2*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/360 + (Real.sqrt 5)^2/36 + (Real.sqrt 5)*(Real.sqrt (10 - 2 * Real.sqrt 5))^2/90 - (Real.sqrt 5)/18 + (Real.sqrt (10 - 2 * Real.sqrt 5))^2/72 + 1/36) * hr2sq + (13*(Real.sqrt 2)*(Real.sqrt 5)^2/900 + 11*(Real.sqrt 2)*(Real.sqrt 5)/360 + (Real.sqrt 2)/72 + 11*(Real.sqrt 5)^2/450 + (Real.sqrt 5)/36 + 5/144) * ht5sq + (-13*(Real.sqrt 2)*(Real.sqrt 5)/450 + (Real.sqrt 2)/9 - 11*(Real.sqrt 5)/225 + 181/720) * hs5sq]
  rw [show (1:ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
  apply Real.sqrt_le_sqrt
  nlinarith [hs5le, Real.sqrt_nonneg 5, Real.sqrt_nonneg 2,
    Real.sqrt_nonneg (10 - 2 * Real.sqrt 5), hr2sq,
    mul_nonneg (Real.sqrt_nonneg 2) (Real.sqrt_nonneg 5)]

private lemma qne01 : pb0 ≠ pb1 := ne_of_dist_one' qd01
private lemma qne02 : pb0 ≠ pb2 := ne_of_dist_ge_one qge02
private lemma qne03 : pb0 ≠ pb3 := ne_of_dist_ge_one qge03
private lemma qne04 : pb0 ≠ pb4 := ne_of_dist_one' qd04
private lemma qne05 : pb0 ≠ pb5 := ne_of_dist_one' qd05
private lemma qne06 : pb0 ≠ pb6 := ne_of_dist_one' qd06
private lemma qne07 : pb0 ≠ pb7 := ne_of_dist_one' qd07
private lemma qne12 : pb1 ≠ pb2 := ne_of_dist_one' qd12
private lemma qne13 : pb1 ≠ pb3 := ne_of_dist_ge_one qge13
private lemma qne14 : pb1 ≠ pb4 := ne_of_dist_ge_one qge14
private lemma qne15 : pb1 ≠ pb5 := ne_of_dist_one' qd15
private lemma qne16 : pb1 ≠ pb6 := ne_of_dist_one' qd16
private lemma qne17 : pb1 ≠ pb7 := ne_of_dist_one' qd17
private lemma qne23 : pb2 ≠ pb3 := ne_of_dist_one' qd23
private lemma qne24 : pb2 ≠ pb4 := ne_of_dist_ge_one qge24
private lemma qne25 : pb2 ≠ pb5 := ne_of_dist_one' qd25
private lemma qne26 : pb2 ≠ pb6 := ne_of_dist_one' qd26
private lemma qne27 : pb2 ≠ pb7 := ne_of_dist_ge_one qge27
private lemma qne34 : pb3 ≠ pb4 := ne_of_dist_one' qd34
private lemma qne35 : pb3 ≠ pb5 := ne_of_dist_one' qd35
private lemma qne36 : pb3 ≠ pb6 := ne_of_dist_one' qd36
private lemma qne37 : pb3 ≠ pb7 := ne_of_dist_ge_one qge37
private lemma qne45 : pb4 ≠ pb5 := ne_of_dist_one' qd45
private lemma qne46 : pb4 ≠ pb6 := ne_of_dist_one' qd46
private lemma qne47 : pb4 ≠ pb7 := ne_of_dist_ge_one qge47
private lemma qne56 : pb5 ≠ pb6 := ne_of_dist_ge_one qge56
private lemma qne57 : pb5 ≠ pb7 := ne_of_dist_one' qd57
private lemma qne67 : pb6 ≠ pb7 := ne_of_dist_ge_one qge67

end Cap8Distances

section Cap8Config

private lemma cap8_dist : ∀ u ∈ capBipyr8, ∀ v ∈ capBipyr8, u ≠ v → 1 ≤ dist u v := by
  have key : ∀ a b : E3, dist a b = 1 → 1 ≤ dist a b ∧ 1 ≤ dist b a := by
    intro a b h
    exact ⟨by rw [h], by rw [dist_comm, h]⟩
  have key2 : ∀ a b : E3, 1 ≤ dist a b → 1 ≤ dist a b ∧ 1 ≤ dist b a := by
    intro a b h
    exact ⟨h, by rw [dist_comm]; exact h⟩
  intro u hu v hv huv
  simp only [capBipyr8, Finset.mem_insert, Finset.mem_singleton] at hu hv
  rcases hu with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    rcases hv with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    first
      | exact absurd rfl huv
      | exact (key _ _ qd01).1 | exact (key _ _ qd01).2
      | exact (key _ _ qd12).1 | exact (key _ _ qd12).2
      | exact (key _ _ qd23).1 | exact (key _ _ qd23).2
      | exact (key _ _ qd34).1 | exact (key _ _ qd34).2
      | exact (key _ _ qd04).1 | exact (key _ _ qd04).2
      | exact (key _ _ qd05).1 | exact (key _ _ qd05).2
      | exact (key _ _ qd15).1 | exact (key _ _ qd15).2
      | exact (key _ _ qd25).1 | exact (key _ _ qd25).2
      | exact (key _ _ qd35).1 | exact (key _ _ qd35).2
      | exact (key _ _ qd45).1 | exact (key _ _ qd45).2
      | exact (key _ _ qd06).1 | exact (key _ _ qd06).2
      | exact (key _ _ qd16).1 | exact (key _ _ qd16).2
      | exact (key _ _ qd26).1 | exact (key _ _ qd26).2
      | exact (key _ _ qd36).1 | exact (key _ _ qd36).2
      | exact (key _ _ qd46).1 | exact (key _ _ qd46).2
      | exact (key _ _ qd07).1 | exact (key _ _ qd07).2
      | exact (key _ _ qd17).1 | exact (key _ _ qd17).2
      | exact (key _ _ qd57).1 | exact (key _ _ qd57).2
      | exact (key2 _ _ qge02).1 | exact (key2 _ _ qge02).2
      | exact (key2 _ _ qge03).1 | exact (key2 _ _ qge03).2
      | exact (key2 _ _ qge13).1 | exact (key2 _ _ qge13).2
      | exact (key2 _ _ qge14).1 | exact (key2 _ _ qge14).2
      | exact (key2 _ _ qge24).1 | exact (key2 _ _ qge24).2
      | exact (key2 _ _ qge56).1 | exact (key2 _ _ qge56).2
      | exact (key2 _ _ qge27).1 | exact (key2 _ _ qge27).2
      | exact (key2 _ _ qge37).1 | exact (key2 _ _ qge37).2
      | exact (key2 _ _ qge47).1 | exact (key2 _ _ qge47).2
      | exact (key2 _ _ qge67).1 | exact (key2 _ _ qge67).2

theorem hardCore_capBipyr8 : HardCore capBipyr8 := cap8_dist

theorem card_capBipyr8 : capBipyr8.card = 8 := by
  rw [capBipyr8]
  rw [Finset.card_insert_of_notMem (by simp [qne01, qne02, qne03, qne04, qne05, qne06, qne07])]
  rw [Finset.card_insert_of_notMem (by simp [qne12, qne13, qne14, qne15, qne16, qne17])]
  rw [Finset.card_insert_of_notMem (by simp [qne23, qne24, qne25, qne26, qne27])]
  rw [Finset.card_insert_of_notMem (by simp [qne34, qne35, qne36, qne37])]
  rw [Finset.card_insert_of_notMem (by simp [qne45, qne46, qne47])]
  rw [Finset.card_insert_of_notMem (by simp [qne56, qne57])]
  rw [Finset.card_insert_of_notMem (by simp [qne67])]
  rw [Finset.card_singleton]

private lemma qdeg0 : 5 ≤ (neighbors capBipyr8 pb0).card := by
  have hsub : ({pb1, pb4, pb5, pb6, pb7} : Finset E3) ⊆ neighbors capBipyr8 pb0 := by
    intro u hu
    simp only [Finset.mem_insert, Finset.mem_singleton] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd01⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd04⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd05⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd06⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd07⟩
  have hcard : ({pb1, pb4, pb5, pb6, pb7} : Finset E3).card = 5 := by
    rw [Finset.card_insert_of_notMem (by simp [qne14, qne15, qne16, qne17])]
    rw [Finset.card_insert_of_notMem (by simp [qne45, qne46, qne47])]
    rw [Finset.card_insert_of_notMem (by simp [qne56, qne57])]
    rw [Finset.card_insert_of_notMem (by simp [qne67])]
    rw [Finset.card_singleton]
  calc 5 = ({pb1, pb4, pb5, pb6, pb7} : Finset E3).card := hcard.symm
    _ ≤ _ := Finset.card_le_card hsub

private lemma qdeg1 : 5 ≤ (neighbors capBipyr8 pb1).card := by
  have hsub : ({pb0, pb2, pb5, pb6, pb7} : Finset E3) ⊆ neighbors capBipyr8 pb1 := by
    intro u hu
    simp only [Finset.mem_insert, Finset.mem_singleton] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd01⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd12⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd15⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd16⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd17⟩
  have hcard : ({pb0, pb2, pb5, pb6, pb7} : Finset E3).card = 5 := by
    rw [Finset.card_insert_of_notMem (by simp [qne02, qne05, qne06, qne07])]
    rw [Finset.card_insert_of_notMem (by simp [qne25, qne26, qne27])]
    rw [Finset.card_insert_of_notMem (by simp [qne56, qne57])]
    rw [Finset.card_insert_of_notMem (by simp [qne67])]
    rw [Finset.card_singleton]
  calc 5 = ({pb0, pb2, pb5, pb6, pb7} : Finset E3).card := hcard.symm
    _ ≤ _ := Finset.card_le_card hsub

private lemma qdeg2 : 4 ≤ (neighbors capBipyr8 pb2).card := by
  have hsub : ({pb1, pb3, pb5, pb6} : Finset E3) ⊆ neighbors capBipyr8 pb2 := by
    intro u hu
    simp only [Finset.mem_insert, Finset.mem_singleton] at hu
    rcases hu with rfl | rfl | rfl | rfl
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd12⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd23⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd25⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd26⟩
  have hcard : ({pb1, pb3, pb5, pb6} : Finset E3).card = 4 := by
    rw [Finset.card_insert_of_notMem (by simp [qne13, qne15, qne16])]
    rw [Finset.card_insert_of_notMem (by simp [qne35, qne36])]
    rw [Finset.card_insert_of_notMem (by simp [qne56])]
    rw [Finset.card_singleton]
  calc 4 = ({pb1, pb3, pb5, pb6} : Finset E3).card := hcard.symm
    _ ≤ _ := Finset.card_le_card hsub

private lemma qdeg3 : 4 ≤ (neighbors capBipyr8 pb3).card := by
  have hsub : ({pb2, pb4, pb5, pb6} : Finset E3) ⊆ neighbors capBipyr8 pb3 := by
    intro u hu
    simp only [Finset.mem_insert, Finset.mem_singleton] at hu
    rcases hu with rfl | rfl | rfl | rfl
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd23⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd34⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd35⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd36⟩
  have hcard : ({pb2, pb4, pb5, pb6} : Finset E3).card = 4 := by
    rw [Finset.card_insert_of_notMem (by simp [qne24, qne25, qne26])]
    rw [Finset.card_insert_of_notMem (by simp [qne45, qne46])]
    rw [Finset.card_insert_of_notMem (by simp [qne56])]
    rw [Finset.card_singleton]
  calc 4 = ({pb2, pb4, pb5, pb6} : Finset E3).card := hcard.symm
    _ ≤ _ := Finset.card_le_card hsub

private lemma qdeg4 : 4 ≤ (neighbors capBipyr8 pb4).card := by
  have hsub : ({pb0, pb3, pb5, pb6} : Finset E3) ⊆ neighbors capBipyr8 pb4 := by
    intro u hu
    simp only [Finset.mem_insert, Finset.mem_singleton] at hu
    rcases hu with rfl | rfl | rfl | rfl
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd04⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd34⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd45⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd46⟩
  have hcard : ({pb0, pb3, pb5, pb6} : Finset E3).card = 4 := by
    rw [Finset.card_insert_of_notMem (by simp [qne03, qne05, qne06])]
    rw [Finset.card_insert_of_notMem (by simp [qne35, qne36])]
    rw [Finset.card_insert_of_notMem (by simp [qne56])]
    rw [Finset.card_singleton]
  calc 4 = ({pb0, pb3, pb5, pb6} : Finset E3).card := hcard.symm
    _ ≤ _ := Finset.card_le_card hsub

private lemma qdeg5 : 6 ≤ (neighbors capBipyr8 pb5).card := by
  have hsub : ({pb0, pb1, pb2, pb3, pb4, pb7} : Finset E3) ⊆ neighbors capBipyr8 pb5 := by
    intro u hu
    simp only [Finset.mem_insert, Finset.mem_singleton] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl | rfl
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd05⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd15⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd25⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd35⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd45⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], qd57⟩
  have hcard : ({pb0, pb1, pb2, pb3, pb4, pb7} : Finset E3).card = 6 := by
    rw [Finset.card_insert_of_notMem (by simp [qne01, qne02, qne03, qne04, qne07])]
    rw [Finset.card_insert_of_notMem (by simp [qne12, qne13, qne14, qne17])]
    rw [Finset.card_insert_of_notMem (by simp [qne23, qne24, qne27])]
    rw [Finset.card_insert_of_notMem (by simp [qne34, qne37])]
    rw [Finset.card_insert_of_notMem (by simp [qne47])]
    rw [Finset.card_singleton]
  calc 6 = ({pb0, pb1, pb2, pb3, pb4, pb7} : Finset E3).card := hcard.symm
    _ ≤ _ := Finset.card_le_card hsub

private lemma qdeg6 : 5 ≤ (neighbors capBipyr8 pb6).card := by
  have hsub : ({pb0, pb1, pb2, pb3, pb4} : Finset E3) ⊆ neighbors capBipyr8 pb6 := by
    intro u hu
    simp only [Finset.mem_insert, Finset.mem_singleton] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd06⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd16⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd26⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd36⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd46⟩
  have hcard : ({pb0, pb1, pb2, pb3, pb4} : Finset E3).card = 5 := by
    rw [Finset.card_insert_of_notMem (by simp [qne01, qne02, qne03, qne04])]
    rw [Finset.card_insert_of_notMem (by simp [qne12, qne13, qne14])]
    rw [Finset.card_insert_of_notMem (by simp [qne23, qne24])]
    rw [Finset.card_insert_of_notMem (by simp [qne34])]
    rw [Finset.card_singleton]
  calc 5 = ({pb0, pb1, pb2, pb3, pb4} : Finset E3).card := hcard.symm
    _ ≤ _ := Finset.card_le_card hsub

private lemma qdeg7 : 3 ≤ (neighbors capBipyr8 pb7).card := by
  have hsub : ({pb0, pb1, pb5} : Finset E3) ⊆ neighbors capBipyr8 pb7 := by
    intro u hu
    simp only [Finset.mem_insert, Finset.mem_singleton] at hu
    rcases hu with rfl | rfl | rfl
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd07⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd17⟩
    · exact Finset.mem_filter.mpr ⟨by simp [capBipyr8], by rw [dist_comm]; exact qd57⟩
  have hcard : ({pb0, pb1, pb5} : Finset E3).card = 3 := by
    rw [Finset.card_insert_of_notMem (by simp [qne01, qne05])]
    rw [Finset.card_insert_of_notMem (by simp [qne15])]
    rw [Finset.card_singleton]
  calc 3 = ({pb0, pb1, pb5} : Finset E3).card := hcard.symm
    _ ≤ _ := Finset.card_le_card hsub

/-- **Eight particles reach `E = −18`**: the capped pentagonal bipyramid carries
36 ordered contacts. (The matching lower bound is the `E_min(8)` programme.) -/
theorem energy_capBipyr8_le : energy capBipyr8 ≤ -18 := by
  have hcc : 36 ≤ contactCount capBipyr8 := by
    rw [contactCount, capBipyr8]
    rw [Finset.sum_insert (by simp [qne01, qne02, qne03, qne04, qne05, qne06, qne07])]
    rw [Finset.sum_insert (by simp [qne12, qne13, qne14, qne15, qne16, qne17])]
    rw [Finset.sum_insert (by simp [qne23, qne24, qne25, qne26, qne27])]
    rw [Finset.sum_insert (by simp [qne34, qne35, qne36, qne37])]
    rw [Finset.sum_insert (by simp [qne45, qne46, qne47])]
    rw [Finset.sum_insert (by simp [qne56, qne57])]
    rw [Finset.sum_insert (by simp [qne67])]
    rw [Finset.sum_singleton]
    simp only [show ({pb0, pb1, pb2, pb3, pb4, pb5, pb6, pb7} : Finset E3) = capBipyr8 from rfl]
    have h0 := qdeg0; have h1 := qdeg1; have h2 := qdeg2; have h3 := qdeg3
    have h4 := qdeg4; have h5 := qdeg5; have h6 := qdeg6; have h7 := qdeg7
    omega
  rw [energy]
  have : (36 : ℝ) ≤ (contactCount capBipyr8 : ℝ) := by exact_mod_cast hcc
  linarith

end Cap8Config

end Kissing3D
