import ContactNumbers.Emin8Final
import ContactNumbers.Emin9Kills
import ContactNumbers.Emin9Canon
import ContactNumbers.Emin9P7
import ContactNumbers.Emin9P3
import ContactNumbers.Emin9P0
import ContactNumbers.Emin9C23
import ContactNumbers.Emin9Q0
import ContactNumbers.Emin9Q4
import ContactNumbers.Emin9Q10
import ContactNumbers.Emin9Q1
import ContactNumbers.Emin9Q12
import ContactNumbers.Emin9Q28
import ContactNumbers.Emin9Q30
import ContactNumbers.Emin9Q37

set_option linter.style.header false
set_option linter.unusedSimpArgs false
set_option maxHeartbeats 4000000
set_option maxRecDepth 200000

/-!
# Towards `E_min(9) = −21`: the assembly layer

Machine-generated by `scratch-h4/emin9_gen.py`, porting the `Emin8` walk
architecture to the 36 pair decisions of `Fin 9` with base-16 certificate
fields, and adding the new geometric kill patterns (P6, SOS obstruction
lemmas, and full survivor-class certificates).
-/

namespace Kissing3D

open Finset

open scoped Classical in
/-- **Minimum degree four** for nine particles: at `43` or more ordered contacts,
deleting a degree-`≤3` particle would leave eight particles with `≥ 37` ordered
contacts, contradicting `eight_particle_bound`. -/
theorem degree_ge_four_9 {X : Finset E3} (hX : HardCore X) (h9 : X.card = 9)
    (hcc : 43 ≤ contactCount X) : ∀ v ∈ X, 4 ≤ (neighbors X v).card := by
  intro v hv
  by_contra hlt
  push_neg at hlt
  have herase := contactCount_erase (X := X) (v := v) hv
  have hY : (X.erase v).card = 8 := by rw [Finset.card_erase_of_mem hv, h9]
  have hXY : HardCore (X.erase v) := fun a ha b hb hab =>
    hX a (Finset.mem_of_mem_erase ha) b (Finset.mem_of_mem_erase hb) hab
  have hbound := eight_particle_bound hXY hY
  omega

namespace Emin9T

/-- Index of the pair `{i, j}` (for `i < j < 9`) in incremental order. -/
def pairIdx9 (i j : ℕ) : ℕ :=
  let a := min i j
  let b := max i j
  b * (b - 1) / 2 + a

/-- Bond test against the decided edge list. -/
def eMem (es : List ℕ) (i j : ℕ) : Bool :=
  decide (i < 9) && decide (j < 9) && (i != j) && es.contains (pairIdx9 i j)

/-- Base-16 payload field `k` of a packed certificate (after the base-64 kind digit). -/
def fld (cert k : ℕ) : ℕ := cert / (64 * 16 ^ k) % 16

/-- Certificate check against the decided edge and non-edge index lists. -/
def checkCert (es ns : List ℕ) (cert : ℕ) : Bool :=
  let kind := cert % 64
  if kind == 0 then
    let v := fld cert 0
    decide (v < 9) &&
      decide (5 ≤ (ns.filter (fun k => (cPairFst k == v) || (cPairSnd k == v))).length)
  else if kind == 1 then
    decide (15 ≤ ns.length)
  else if kind == 2 then
    let a := fld cert 0; let b := fld cert 1; let c := fld cert 2
    let d := fld cert 3; let e := fld cert 4
    eMem es a b && eMem es a c && eMem es a d && eMem es a e &&
    eMem es b c && eMem es b d && eMem es b e &&
    eMem es c d && eMem es c e && eMem es d e
  else if kind == 3 then
    let u := fld cert 0; let v := fld cert 1; let c := fld cert 2
    let x := fld cert 3; let y := fld cert 4; let z := fld cert 5
    eMem es u v && eMem es u c && eMem es v c && eMem es u x && eMem es v x &&
    eMem es u y && eMem es v y && eMem es u z && eMem es v z &&
    eMem es c x && eMem es c y && eMem es c z &&
    (x != y) && (x != z) && (y != z)
  else if kind == 4 then
    let u := fld cert 0; let v := fld cert 1
    let w1 := fld cert 2; let w2 := fld cert 3; let w3 := fld cert 4
    let w4 := fld cert 5; let w5 := fld cert 6; let w6 := fld cert 7
    eMem es u v &&
    eMem es u w1 && eMem es v w1 && eMem es u w2 && eMem es v w2 &&
    eMem es u w3 && eMem es v w3 && eMem es u w4 && eMem es v w4 &&
    eMem es u w5 && eMem es v w5 && eMem es u w6 && eMem es v w6 &&
    (w1 != w2) && (w1 != w3) && (w1 != w4) && (w1 != w5) && (w1 != w6) &&
    (w2 != w3) && (w2 != w4) && (w2 != w5) && (w2 != w6) &&
    (w3 != w4) && (w3 != w5) && (w3 != w6) &&
    (w4 != w5) && (w4 != w6) && (w5 != w6)
  else if kind == 5 then
    let a := fld cert 0; let b := fld cert 1; let c := fld cert 2
    let w1 := fld cert 3; let w2 := fld cert 4; let w3 := fld cert 5
    (a != b) && (a != c) && (b != c) &&
    (w1 != w2) && (w1 != w3) && (w2 != w3) &&
    eMem es a w1 && eMem es b w1 && eMem es c w1 &&
    eMem es a w2 && eMem es b w2 && eMem es c w2 &&
    eMem es a w3 && eMem es b w3 && eMem es c w3
  else if kind == 6 then
    let m := fun t => fld cert t
    (List.range 7).all (fun t => decide (m t < 9)) &&
    ((List.range 7).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 3) && eMem es (m 0) (m 4) && eMem es (m 0) (m 5) &&
    eMem es (m 1) (m 2) && eMem es (m 1) (m 4) && eMem es (m 1) (m 5) &&
    eMem es (m 2) (m 3) && eMem es (m 2) (m 4) && eMem es (m 3) (m 4) &&
    eMem es (m 0) (m 6) && eMem es (m 1) (m 6) && eMem es (m 2) (m 6) &&
    eMem es (m 3) (m 6) && eMem es (m 4) (m 6) && eMem es (m 5) (m 6)
  else if kind == 7 then
    let m := fun t => fld cert t
    (List.range 7).all (fun t => decide (m t < 9)) &&
    ((List.range 7).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 4) && eMem es (m 0) (m 5) &&
    eMem es (m 1) (m 2) && eMem es (m 1) (m 3) && eMem es (m 2) (m 3) &&
    eMem es (m 2) (m 5) && eMem es (m 3) (m 4) && eMem es (m 4) (m 5) &&
    eMem es (m 0) (m 6) && eMem es (m 1) (m 6) && eMem es (m 2) (m 6) &&
    eMem es (m 3) (m 6) && eMem es (m 4) (m 6) && eMem es (m 5) (m 6)
  else if kind == 8 then
    let m := fun t => fld cert t
    (List.range 7).all (fun t => decide (m t < 9)) &&
    ((List.range 7).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 3) && eMem es (m 0) (m 4) && eMem es (m 0) (m 5) &&
    eMem es (m 1) (m 2) && eMem es (m 1) (m 4) && eMem es (m 1) (m 5) &&
    eMem es (m 2) (m 3) && eMem es (m 2) (m 5) && eMem es (m 3) (m 4) &&
    eMem es (m 1) (m 6) && eMem es (m 2) (m 6) && eMem es (m 3) (m 6) &&
    eMem es (m 4) (m 6) && eMem es (m 5) (m 6)
  else if kind == 9 then
    -- canonicity: permutation m whose determined image dominates the prefix at i
    let m := fun t => fld cert t
    let i := fld cert 9 + 16 * fld cert 10
    (List.range 9).all (fun t => decide (m t < 9)) &&
    ((List.range 9).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    decide (i < 36) &&
    ((List.range i).all fun j =>
      ((es.contains j && es.contains (pairIdx9 (m (cPairFst j)) (m (cPairSnd j)))) ||
       (ns.contains j && ns.contains (pairIdx9 (m (cPairFst j)) (m (cPairSnd j)))))) &&
    ns.contains i &&
    es.contains (pairIdx9 (m (cPairFst i)) (m (cPairSnd i)))
  else if kind == 10 then
    let m := fun t => fld cert t
    (List.range 6).all (fun t => decide (m t < 9)) &&
    ((List.range 6).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 1) (m 2) && eMem es (m 1) (m 3) &&
    eMem es (m 1) (m 5) && eMem es (m 2) (m 3) && eMem es (m 2) (m 5) &&
    eMem es (m 3) (m 5) && eMem es (m 4) (m 5)
  else if kind == 11 then
    let m := fun t => fld cert t
    (List.range 7).all (fun t => decide (m t < 9)) &&
    ((List.range 7).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 5) && eMem es (m 0) (m 6) &&
    eMem es (m 1) (m 2) && eMem es (m 1) (m 3) && eMem es (m 1) (m 4) &&
    eMem es (m 2) (m 3) && eMem es (m 2) (m 4) && eMem es (m 3) (m 5) &&
    eMem es (m 4) (m 6) && eMem es (m 5) (m 6)
  else if kind == 12 then
    let m := fun t => fld cert t
    (List.range 7).all (fun t => decide (m t < 9)) &&
    ((List.range 7).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 1) (m 2) && eMem es (m 1) (m 3) &&
    eMem es (m 1) (m 4) && eMem es (m 1) (m 5) && eMem es (m 2) (m 3) &&
    eMem es (m 2) (m 5) && eMem es (m 3) (m 5) && eMem es (m 3) (m 6) &&
    eMem es (m 4) (m 6) && eMem es (m 5) (m 6)
  else if kind == 13 then
    let m := fun t => fld cert t
    (List.range 7).all (fun t => decide (m t < 9)) &&
    ((List.range 7).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 5) && eMem es (m 1) (m 2) &&
    eMem es (m 1) (m 3) && eMem es (m 1) (m 4) && eMem es (m 1) (m 5) &&
    eMem es (m 2) (m 3) && eMem es (m 2) (m 4) && eMem es (m 3) (m 5) &&
    eMem es (m 4) (m 6) && eMem es (m 5) (m 6)
  else if kind == 14 then
    let m := fun t => fld cert t
    (List.range 9).all (fun t => decide (m t < 9)) &&
    ((List.range 9).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 5) && eMem es (m 0) (m 6) &&
    eMem es (m 0) (m 7) && eMem es (m 1) (m 2) && eMem es (m 1) (m 3) &&
    eMem es (m 1) (m 4) && eMem es (m 1) (m 5) && eMem es (m 1) (m 6) &&
    eMem es (m 1) (m 8) && eMem es (m 2) (m 4) && eMem es (m 2) (m 7) &&
    eMem es (m 2) (m 8) && eMem es (m 3) (m 5) && eMem es (m 3) (m 7) &&
    eMem es (m 3) (m 8) && eMem es (m 4) (m 6) && eMem es (m 5) (m 6) &&
    eMem es (m 7) (m 8)
  else if kind == 15 then
    let m := fun t => fld cert t
    (List.range 8).all (fun t => decide (m t < 9)) &&
    ((List.range 8).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 5) && eMem es (m 0) (m 6) &&
    eMem es (m 0) (m 7) && eMem es (m 1) (m 2) && eMem es (m 1) (m 3) &&
    eMem es (m 1) (m 4) && eMem es (m 2) (m 3) && eMem es (m 2) (m 5) &&
    eMem es (m 3) (m 6) && eMem es (m 3) (m 7) && eMem es (m 4) (m 5) &&
    eMem es (m 4) (m 6) && eMem es (m 5) (m 7) && eMem es (m 6) (m 7)
  else if kind == 16 then
    let m := fun t => fld cert t
    (List.range 8).all (fun t => decide (m t < 9)) &&
    ((List.range 8).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 5) && eMem es (m 0) (m 6) &&
    eMem es (m 1) (m 2) && eMem es (m 1) (m 3) && eMem es (m 1) (m 4) &&
    eMem es (m 1) (m 7) && eMem es (m 2) (m 3) && eMem es (m 2) (m 5) &&
    eMem es (m 3) (m 6) && eMem es (m 3) (m 7) && eMem es (m 4) (m 5) &&
    eMem es (m 4) (m 7) && eMem es (m 5) (m 6) && eMem es (m 6) (m 7)
  else if kind == 17 then
    let m := fun t => fld cert t
    (List.range 8).all (fun t => decide (m t < 9)) &&
    ((List.range 8).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 5) && eMem es (m 0) (m 6) &&
    eMem es (m 1) (m 2) && eMem es (m 1) (m 3) && eMem es (m 1) (m 4) &&
    eMem es (m 1) (m 7) && eMem es (m 2) (m 3) && eMem es (m 2) (m 5) &&
    eMem es (m 3) (m 7) && eMem es (m 4) (m 5) && eMem es (m 4) (m 6) &&
    eMem es (m 4) (m 7) && eMem es (m 5) (m 6) && eMem es (m 6) (m 7)
  else if kind == 18 then
    let m := fun t => fld cert t
    (List.range 8).all (fun t => decide (m t < 9)) &&
    ((List.range 8).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 5) && eMem es (m 0) (m 6) &&
    eMem es (m 1) (m 2) && eMem es (m 1) (m 3) && eMem es (m 1) (m 4) &&
    eMem es (m 1) (m 7) && eMem es (m 2) (m 3) && eMem es (m 2) (m 5) &&
    eMem es (m 2) (m 7) && eMem es (m 3) (m 6) && eMem es (m 4) (m 5) &&
    eMem es (m 4) (m 6) && eMem es (m 4) (m 7) && eMem es (m 5) (m 7)
  else if kind == 19 then
    let m := fun t => fld cert t
    (List.range 8).all (fun t => decide (m t < 9)) &&
    ((List.range 8).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 5) && eMem es (m 1) (m 2) &&
    eMem es (m 1) (m 3) && eMem es (m 1) (m 4) && eMem es (m 1) (m 6) &&
    eMem es (m 2) (m 3) && eMem es (m 2) (m 5) && eMem es (m 2) (m 7) &&
    eMem es (m 3) (m 6) && eMem es (m 3) (m 7) && eMem es (m 4) (m 5) &&
    eMem es (m 4) (m 6) && eMem es (m 5) (m 7) && eMem es (m 6) (m 7)
  else if kind == 20 then
    let m := fun t => fld cert t
    (List.range 8).all (fun t => decide (m t < 9)) &&
    ((List.range 8).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 7) && eMem es (m 1) (m 2) &&
    eMem es (m 1) (m 3) && eMem es (m 1) (m 5) && eMem es (m 1) (m 7) &&
    eMem es (m 2) (m 4) && eMem es (m 2) (m 5) && eMem es (m 2) (m 6) &&
    eMem es (m 3) (m 4) && eMem es (m 3) (m 5) && eMem es (m 4) (m 6) &&
    eMem es (m 5) (m 6) && eMem es (m 6) (m 7)
  else if kind == 21 then
    let m := fun t => fld cert t
    (List.range 8).all (fun t => decide (m t < 9)) &&
    ((List.range 8).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 6) && eMem es (m 0) (m 7) &&
    eMem es (m 1) (m 2) && eMem es (m 1) (m 3) && eMem es (m 1) (m 5) &&
    eMem es (m 2) (m 4) && eMem es (m 2) (m 5) && eMem es (m 3) (m 5) &&
    eMem es (m 3) (m 6) && eMem es (m 3) (m 7) && eMem es (m 4) (m 5) &&
    eMem es (m 4) (m 6) && eMem es (m 4) (m 7) && eMem es (m 5) (m 6)
  else if kind == 22 then
    let m := fun t => fld cert t
    (List.range 8).all (fun t => decide (m t < 9)) &&
    ((List.range 8).all fun t => ((List.range t).all fun t' => m t != m t')) &&
    eMem es (m 0) (m 1) && eMem es (m 0) (m 2) && eMem es (m 0) (m 3) &&
    eMem es (m 0) (m 4) && eMem es (m 0) (m 7) && eMem es (m 1) (m 2) &&
    eMem es (m 1) (m 3) && eMem es (m 1) (m 5) && eMem es (m 1) (m 7) &&
    eMem es (m 2) (m 4) && eMem es (m 2) (m 5) && eMem es (m 3) (m 5) &&
    eMem es (m 3) (m 6) && eMem es (m 4) (m 5) && eMem es (m 4) (m 6) &&
    eMem es (m 4) (m 7) && eMem es (m 5) (m 6) && eMem es (m 6) (m 7)
  else false

/-- Walk the serialized tree: `0` = branch on pair `k`, odd = kill leaf. -/
def walk : ℕ → List ℕ → ℕ → List ℕ → List ℕ → Option (List ℕ)
  | 0, _, _, _, _ => none
  | _, [], _, _, _ => none
  | fuel + 1, c :: rest, k, es, ns =>
    if c == 0 then
      if k < 36 then
        match walk fuel rest (k + 1) (k :: es) ns with
        | none => none
        | some rest2 => walk fuel rest2 (k + 1) es (k :: ns)
      else none
    else if checkCert es ns ((c - 1) / 2) then some rest else none

/-- Composition: a sub-walk returning remainder `r` extends over an appended tail. -/
lemma walk_append {fuel : ℕ} {l1 l2 r : List ℕ} {k : ℕ} {es ns : List ℕ}
    (h : walk fuel l1 k es ns = some r) :
    walk fuel (l1 ++ l2) k es ns = some (r ++ l2) := by
  induction fuel generalizing l1 r k es ns with
  | zero => simp [walk] at h
  | succ fuel ih =>
    match l1 with
    | [] => simp [walk] at h
    | c :: rest =>
      rw [List.cons_append]
      rw [show walk (fuel + 1) (c :: rest) k es ns
          = (if c == 0 then
              if k < 36 then
                match walk fuel rest (k + 1) (k :: es) ns with
                | none => none
                | some rest2 => walk fuel rest2 (k + 1) es (k :: ns)
              else none
            else if checkCert es ns ((c - 1) / 2) then some rest else none) from rfl] at h
      rw [show walk (fuel + 1) ((c :: (rest ++ l2))) k es ns
          = (if c == 0 then
              if k < 36 then
                match walk fuel (rest ++ l2) (k + 1) (k :: es) ns with
                | none => none
                | some rest2 => walk fuel rest2 (k + 1) es (k :: ns)
              else none
            else if checkCert es ns ((c - 1) / 2) then some (rest ++ l2)
            else none) from rfl]
      by_cases hc : c == 0
      · rw [if_pos hc] at h ⊢
        by_cases hk : k < 36
        · rw [if_pos hk] at h ⊢
          cases hw : walk fuel rest (k + 1) (k :: es) ns with
          | none => rw [hw] at h; simp at h
          | some rest2 =>
            rw [hw] at h
            simp only at h
            rw [ih hw]
            simp only
            exact ih h
        · rw [if_neg hk] at h
          exact absurd h (by simp)
      · rw [if_neg hc] at h ⊢
        by_cases hcc : checkCert es ns ((c - 1) / 2)
        · rw [if_pos hcc] at h ⊢
          simp only [Option.some.injEq] at h
          rw [h]
        · rw [if_neg hcc] at h
          exact absurd h (by simp)

/-- Codec facts, kernel-checked. -/
lemma pair_codec : ∀ i < 9, ∀ j < 9, i ≠ j →
    pairIdx9 i j < 36 ∧ cPairFst (pairIdx9 i j) = min i j ∧
      cPairSnd (pairIdx9 i j) = max i j := by decide

lemma pair_decode_inj : ∀ i < 36, ∀ i' < 36,
    cPairFst i = cPairFst i' → cPairSnd i = cPairSnd i' → i = i' := by decide

lemma pair_decode_lt : ∀ i < 36, cPairFst i < cPairSnd i ∧ cPairSnd i < 9 := by decide


private def ptn (v k : ℕ) : ℕ := if cPairFst k = v then cPairSnd k else cPairFst k

/-- Interpret a raw certificate vertex as a particle. -/
private def qf (p : Fin 9 → E3) (n : ℕ) : E3 := p ⟨n % 9, Nat.mod_lt _ (by norm_num)⟩

open scoped Classical in
/-- **Certificate soundness**: no verified kill certificate is compatible with a
hard-core eight-particle realization carrying at least 38 ordered contacts. -/
theorem checkCert_sound {X : Finset E3} (hX : HardCore X) {p : Fin 9 → E3}
    (hpmem : ∀ i, p i ∈ X) (hpinj : Function.Injective p)
    (h9 : X.card = 9) (hXim : Finset.image p Finset.univ = X)
    (hcc : 43 ≤ contactCount X)
    (hmax : ∀ q : Fin 9 → E3, Function.Injective q → Finset.image q Finset.univ = X → bondCode q ≤ bondCode p)
    {es ns : List ℕ}
    (hes : ∀ i ∈ es, i < 36 ∧ dist (qf p (cPairFst i)) (qf p (cPairSnd i)) = 1)
    (hns : ∀ i ∈ ns, i < 36 ∧ ¬ dist (qf p (cPairFst i)) (qf p (cPairSnd i)) = 1)
    (hesnd : es.Nodup) (hnsnd : ns.Nodup)
    {cert : ℕ} (hkill : checkCert es ns cert = true) : False := by
  -- particle-level helpers
  have hqmem : ∀ m : ℕ, qf p m ∈ X := fun m => hpmem _
  have hqne : ∀ {i j : ℕ}, i < 9 → j < 9 → i ≠ j → qf p i ≠ qf p j := by
    intro i j hi hj hne heq
    apply hne
    have hv := hpinj heq
    simp only [Fin.mk.injEq] at hv
    rwa [Nat.mod_eq_of_lt hi, Nat.mod_eq_of_lt hj] at hv
  have hqdist : ∀ {i j : ℕ}, eMem es i j = true → dist (qf p i) (qf p j) = 1 := by
    intro i j h
    simp only [eMem, Bool.and_eq_true, and_assoc, decide_eq_true_eq, bne_iff_ne,
      List.contains_iff_mem] at h
    obtain ⟨hi, hj, hne, hmem⟩ := h
    have hd := (hes _ hmem).2
    obtain ⟨_, hf, hs⟩ := pair_codec i hi j hj hne
    rw [hf, hs] at hd
    rcases lt_or_gt_of_ne hne with h' | h'
    · rwa [min_eq_left h'.le, max_eq_right h'.le] at hd
    · rw [min_eq_right h'.le, max_eq_left h'.le] at hd
      rwa [dist_comm]
  have hqlt : ∀ {i j : ℕ}, eMem es i j = true → i < 9 ∧ j < 9 ∧ i ≠ j := by
    intro i j h
    simp only [eMem, Bool.and_eq_true, and_assoc, decide_eq_true_eq, bne_iff_ne,
      List.contains_iff_mem] at h
    exact ⟨h.1, h.2.1, h.2.2.1⟩
  have hmemN : ∀ {u t : ℕ}, eMem es u t = true → qf p t ∈ neighbors X (qf p u) := by
    intro u t h
    exact Finset.mem_filter.mpr ⟨hqmem t, hqdist h⟩
  have hcomm2 : ∀ {u v t : ℕ}, eMem es u t = true → eMem es v t = true →
      qf p t ∈ neighbors X (qf p u) ∩ neighbors X (qf p v) := by
    intro u v t h1 h2
    exact Finset.mem_inter.mpr ⟨hmemN h1, hmemN h2⟩
  -- dispatch on the kind
  have hb : cert % 64 = 0 ∨
      cert % 64 = 1 ∨
      cert % 64 = 2 ∨
      cert % 64 = 3 ∨
      cert % 64 = 4 ∨
      cert % 64 = 5 ∨
      cert % 64 = 6 ∨
      cert % 64 = 7 ∨
      cert % 64 = 8 ∨
      cert % 64 = 9 ∨
      cert % 64 = 10 ∨
      cert % 64 = 11 ∨
      cert % 64 = 12 ∨
      cert % 64 = 13 ∨
      cert % 64 = 14 ∨
      cert % 64 = 15 ∨
      cert % 64 = 16 ∨
      cert % 64 = 17 ∨
      cert % 64 = 18 ∨
      cert % 64 = 19 ∨
      cert % 64 = 20 ∨
      cert % 64 = 21 ∨
      cert % 64 = 22 ∨
      23 ≤ cert % 64 := by omega
  rcases hb with hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk | hk
  · -- kind 0: min-degree
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    obtain ⟨hv8, hlen⟩ := hkill
    set v := fld cert 0 with hvdef
    set l := ns.filter (fun k => (cPairFst k == v) || (cPairSnd k == v)) with hldef
    have hlsub : ∀ k ∈ l, k ∈ ns ∧ (cPairFst k = v ∨ cPairSnd k = v) := by
      intro k hkmem
      rw [hldef] at hkmem
      have h1 := List.mem_of_mem_filter hkmem
      have h2 := List.of_mem_filter hkmem
      simp only [Bool.or_eq_true, beq_iff_eq] at h2
      exact ⟨h1, h2⟩
    have hlnd : l.Nodup := by
      rw [hldef]
      exact hnsnd.filter _
    have hp1 : ∀ k ∈ l, ptn v k < 9 ∧ ptn v k ≠ v ∧
        ¬ dist (qf p v) (qf p (ptn v k)) = 1 := by
      intro k hkmem
      obtain ⟨hkns, hkinc⟩ := hlsub k hkmem
      obtain ⟨hk28, hnd⟩ := hns k hkns
      obtain ⟨hfs, hs8⟩ := pair_decode_lt k hk28
      by_cases hfeq : cPairFst k = v
      · refine ⟨by simp only [ptn, if_pos hfeq]; omega,
          by simp only [ptn, if_pos hfeq]; omega, ?_⟩
        simp only [ptn, if_pos hfeq]
        rw [← hfeq]
        exact hnd
      · have hseq : cPairSnd k = v := by
          rcases hkinc with hc | hc
          · exact absurd hc hfeq
          · exact hc
        refine ⟨by simp only [ptn, if_neg hfeq]; omega,
          by simp only [ptn, if_neg hfeq]; exact hfeq, ?_⟩
        simp only [ptn, if_neg hfeq]
        intro hd
        apply hnd
        rw [← hseq, dist_comm] at hd
        exact hd
    have hpinj2 : ∀ k ∈ l, ∀ k' ∈ l, ptn v k = ptn v k' → k = k' := by
      intro k hkmem k' hkmem' hpp
      obtain ⟨hkns, hkinc⟩ := hlsub k hkmem
      obtain ⟨hkns', hkinc'⟩ := hlsub k' hkmem'
      obtain ⟨hk28, _⟩ := hns k hkns
      obtain ⟨hk28', _⟩ := hns k' hkns'
      obtain ⟨hlt, h9'⟩ := pair_decode_lt k hk28
      obtain ⟨hlt', h9''⟩ := pair_decode_lt k' hk28'
      simp only [ptn] at hpp
      apply pair_decode_inj k hk28 k' hk28'
      all_goals
        rcases hkinc with hc | hc <;> rcases hkinc' with hc' | hc' <;>
        [ (rw [if_pos hc, if_pos hc'] at hpp);
          (rw [if_pos hc, if_neg (by omega : ¬ cPairFst k' = v)] at hpp);
          (rw [if_neg (by omega : ¬ cPairFst k = v), if_pos hc'] at hpp);
          (rw [if_neg (by omega : ¬ cPairFst k = v),
               if_neg (by omega : ¬ cPairFst k' = v)] at hpp) ] <;>
        omega
    -- the four partner particles exclude four slots of the seven
    have hlen4 : 5 ≤ l.length := hlen
    have hTsub : l.toFinset.card = l.length := List.toFinset_card_of_nodup hlnd
    set PS : Finset E3 := l.toFinset.image (fun k => qf p (ptn v k)) with hPS
    have hPScard : 5 ≤ PS.card := by
      rw [hPS, Finset.card_image_of_injOn]
      · omega
      · intro k hk k' hk' heq
        rw [Finset.mem_coe, List.mem_toFinset] at hk hk'
        obtain ⟨hlt8, _, _⟩ := hp1 k hk
        obtain ⟨hlt8', _, _⟩ := hp1 k' hk'
        by_cases hpe : ptn v k = ptn v k'
        · exact hpinj2 k hk k' hk' hpe
        · exact absurd heq (hqne hlt8 hlt8' hpe).elim
    have hPSdisj : ∀ w ∈ PS, w ∈ X.erase (qf p v) ∧ w ∉ neighbors X (qf p v) := by
      intro w hw
      rw [hPS] at hw
      obtain ⟨k, hk, rfl⟩ := Finset.mem_image.mp hw
      rw [List.mem_toFinset] at hk
      obtain ⟨hlt8, hnev, hnd⟩ := hp1 k hk
      refine ⟨Finset.mem_erase.mpr ⟨hqne hlt8 (by omega) hnev, hqmem _⟩, ?_⟩
      intro hmem
      exact hnd (Finset.mem_filter.mp hmem).2
    have hnb : (neighbors X (qf p v)).card ≤ 3 := by
      have hunion : neighbors X (qf p v) ∪ PS ⊆ X.erase (qf p v) := by
        intro w hw
        rcases Finset.mem_union.mp hw with hw | hw
        · exact Finset.mem_erase.mpr ⟨fun h => by
            have := (Finset.mem_filter.mp hw).2
            rw [h, dist_self] at this
            norm_num at this, (Finset.mem_filter.mp hw).1⟩
        · exact (hPSdisj w hw).1
      have hdisj : Disjoint (neighbors X (qf p v)) PS := by
        rw [Finset.disjoint_right]
        intro w hw
        exact (hPSdisj w hw).2
      have hcard7 : (X.erase (qf p v)).card = 8 := by
        rw [Finset.card_erase_of_mem (hqmem v), h9]
      have := Finset.card_le_card hunion
      rw [Finset.card_union_of_disjoint hdisj] at this
      omega
    have hd4 := degree_ge_four_9 hX h9 (by omega) (qf p v) (hqmem v)
    omega
  · -- kind 1: ten decided non-bonds
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    have hU := Emin8T.contactCount_eq_twice_unordered hpinj hXim
    set U := (Finset.univ : Finset (Fin 9 × Fin 9)).filter
      (fun q => q.1 < q.2 ∧ dist (p q.1) (p q.2) = 1) with hUdef
    have hU19 : 22 ≤ U.card := by omega
    set T : Finset (Fin 9 × Fin 9) := ns.toFinset.image
      (fun k => ((⟨cPairFst k % 9, Nat.mod_lt _ (by norm_num)⟩ : Fin 9),
                 (⟨cPairSnd k % 9, Nat.mod_lt _ (by norm_num)⟩ : Fin 9))) with hTdef
    have hT10 : 15 ≤ T.card := by
      rw [hTdef, Finset.card_image_of_injOn]
      · rw [List.toFinset_card_of_nodup hnsnd]
        exact hkill
      · intro k hk1 k' hk2 heq
        rw [Finset.mem_coe, List.mem_toFinset] at hk1 hk2
        obtain ⟨hk28, _⟩ := hns k hk1
        obtain ⟨hk28', _⟩ := hns k' hk2
        obtain ⟨hlt, h9'⟩ := pair_decode_lt k hk28
        obtain ⟨hlt', h9''⟩ := pair_decode_lt k' hk28'
        have h1 := congrArg (fun q : Fin 9 × Fin 9 => q.1.val) heq
        have h2 := congrArg (fun q : Fin 9 × Fin 9 => q.2.val) heq
        simp only at h1 h2
        rw [Nat.mod_eq_of_lt (by omega), Nat.mod_eq_of_lt (by omega)] at h1
        rw [Nat.mod_eq_of_lt h9', Nat.mod_eq_of_lt h9''] at h2
        exact pair_decode_inj k hk28 k' hk28' h1 h2
    have hTdisjU : Disjoint T U := by
      rw [Finset.disjoint_left]
      intro q hqT hqU
      rw [hTdef] at hqT
      obtain ⟨k, hkmem, rfl⟩ := Finset.mem_image.mp hqT
      rw [List.mem_toFinset] at hkmem
      obtain ⟨hk28, hnd⟩ := hns k hkmem
      have hd := (Finset.mem_filter.mp hqU).2.2
      exact hnd hd
    have hTU : T ∪ U ⊆ (Finset.univ : Finset (Fin 9 × Fin 9)).filter
        (fun q => q.1 < q.2) := by
      intro q hq
      rcases Finset.mem_union.mp hq with hq | hq
      · rw [hTdef] at hq
        obtain ⟨k, hkmem, rfl⟩ := Finset.mem_image.mp hq
        rw [List.mem_toFinset] at hkmem
        obtain ⟨hk28, _⟩ := hns k hkmem
        obtain ⟨hlt, h9'⟩ := pair_decode_lt k hk28
        refine Finset.mem_filter.mpr ⟨Finset.mem_univ _, ?_⟩
        rw [Fin.mk_lt_mk, Nat.mod_eq_of_lt (by omega), Nat.mod_eq_of_lt h9']
        exact hlt
      · exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, (Finset.mem_filter.mp hq).2.1⟩
    have h28 : ((Finset.univ : Finset (Fin 9 × Fin 9)).filter
        (fun q => q.1 < q.2)).card = 36 := by decide
    have hle := Finset.card_le_card hTU
    rw [Finset.card_union_of_disjoint hTdisjU] at hle
    omega
  · -- kind 2: K5
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨h1, h2, h3, h4, h5, h6, h7, h9', h9, h10⟩ := hkill
    exact Emin7.five_points_impossible (hqdist h1) (hqdist h2) (hqdist h3) (hqdist h4)
      (hqdist h5) (hqdist h6) (hqdist h7) (hqdist h9') (hqdist h9) (hqdist h10)
  · -- kind 3: ring degree three
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨huv, huc, hvc, hux, hvx, huy, hvy, huz, hvz, hcx, hcy, hcz,
      hxy, hxz, hyz⟩ := hkill
    obtain ⟨_, hx8, _⟩ := hqlt hux
    obtain ⟨_, hy8, _⟩ := hqlt huy
    obtain ⟨_, hz8, _⟩ := hqlt huz
    exact common_degree_impossible hX (hqdist huv) (hcomm2 huc hvc) (hcomm2 hux hvx)
      (hcomm2 huy hvy) (hcomm2 huz hvz)
      (hqne hx8 hy8 hxy) (hqne hx8 hz8 hxz) (hqne hy8 hz8 hyz)
      (hqdist hcx) (hqdist hcy) (hqdist hcz)
  · -- kind 4: six common neighbours
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨huv, hu1, hv1, hu2, hv2, hu3, hv3, hu4, hv4, hu5, hv5, hu6, hv6,
      h12', h13', h14', h15', h16', h23', h24', h25', h26', h34', h35', h36',
      h45', h46', h56'⟩ := hkill
    obtain ⟨_, hw18, _⟩ := hqlt hu1
    obtain ⟨_, hw28, _⟩ := hqlt hu2
    obtain ⟨_, hw38, _⟩ := hqlt hu3
    obtain ⟨_, hw48, _⟩ := hqlt hu4
    obtain ⟨_, hw58, _⟩ := hqlt hu5
    obtain ⟨_, hw68, _⟩ := hqlt hu6
    have hn12 := hqne hw18 hw28 h12'
    have hn13 := hqne hw18 hw38 h13'
    have hn14 := hqne hw18 hw48 h14'
    have hn15 := hqne hw18 hw58 h15'
    have hn16 := hqne hw18 hw68 h16'
    have hn23 := hqne hw28 hw38 h23'
    have hn24 := hqne hw28 hw48 h24'
    have hn25 := hqne hw28 hw58 h25'
    have hn26 := hqne hw28 hw68 h26'
    have hn34 := hqne hw38 hw48 h34'
    have hn35 := hqne hw38 hw58 h35'
    have hn36 := hqne hw38 hw68 h36'
    have hn45 := hqne hw48 hw58 h45'
    have hn46 := hqne hw48 hw68 h46'
    have hn56 := hqne hw58 hw68 h56'
    have hsub : ({qf p (fld cert 2), qf p (fld cert 3), qf p (fld cert 4),
        qf p (fld cert 5), qf p (fld cert 6), qf p (fld cert 7)} : Finset E3)
        ⊆ neighbors X (qf p (fld cert 0)) ∩ neighbors X (qf p (fld cert 1)) := by
      intro w hw
      simp only [Finset.mem_insert, Finset.mem_singleton] at hw
      rcases hw with rfl | rfl | rfl | rfl | rfl | rfl
      · exact hcomm2 hu1 hv1
      · exact hcomm2 hu2 hv2
      · exact hcomm2 hu3 hv3
      · exact hcomm2 hu4 hv4
      · exact hcomm2 hu5 hv5
      · exact hcomm2 hu6 hv6
    have hcard6 : ({qf p (fld cert 2), qf p (fld cert 3), qf p (fld cert 4),
        qf p (fld cert 5), qf p (fld cert 6), qf p (fld cert 7)} : Finset E3).card = 6 := by
      rw [Finset.card_insert_of_notMem (by simp [hn12, hn13, hn14, hn15, hn16]),
        Finset.card_insert_of_notMem (by simp [hn23, hn24, hn25, hn26]),
        Finset.card_insert_of_notMem (by simp [hn34, hn35, hn36]),
        Finset.card_insert_of_notMem (by simp [hn45, hn46]),
        Finset.card_insert_of_notMem (by simp [hn56]), Finset.card_singleton]
    have hle5 := common_neighbors_le_five hX (hqdist huv)
    have hle6 := Finset.card_le_card hsub
    omega
  · -- kind 5: three particles with three common neighbours
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hab, hac, hbc, h12', h13', h23', haw1, hbw1, hcw1, haw2, hbw2, hcw2,
      haw3, hbw3, hcw3⟩ := hkill
    obtain ⟨ha8, hw18, _⟩ := hqlt haw1
    obtain ⟨hb8, _, _⟩ := hqlt hbw1
    obtain ⟨hc8, _, _⟩ := hqlt hcw1
    obtain ⟨_, hw28, _⟩ := hqlt haw2
    obtain ⟨_, hw38, _⟩ := hqlt haw3
    have hsub : ({qf p (fld cert 3), qf p (fld cert 4), qf p (fld cert 5)} : Finset E3)
        ⊆ neighbors X (qf p (fld cert 0)) ∩
          (neighbors X (qf p (fld cert 1)) ∩ neighbors X (qf p (fld cert 2))) := by
      intro w hw
      simp only [Finset.mem_insert, Finset.mem_singleton] at hw
      rcases hw with rfl | rfl | rfl
      · exact Finset.mem_inter.mpr ⟨hmemN haw1, Finset.mem_inter.mpr ⟨hmemN hbw1, hmemN hcw1⟩⟩
      · exact Finset.mem_inter.mpr ⟨hmemN haw2, Finset.mem_inter.mpr ⟨hmemN hbw2, hmemN hcw2⟩⟩
      · exact Finset.mem_inter.mpr ⟨hmemN haw3, Finset.mem_inter.mpr ⟨hmemN hbw3, hmemN hcw3⟩⟩
    have hcard3 : ({qf p (fld cert 3), qf p (fld cert 4), qf p (fld cert 5)} :
        Finset E3).card = 3 := by
      rw [Finset.card_insert_of_notMem (by
          simp [hqne hw18 hw28 h12', hqne hw18 hw38 h13']),
        Finset.card_insert_of_notMem (by
          simp [hqne hw28 hw38 h23']), Finset.card_singleton]
    have hle2 := common_neighbors_triple_le_two X
      (hqne ha8 hb8 hab) (hqne ha8 hc8 hac) (hqne hb8 hc8 hbc)
    have hle := Finset.card_le_card hsub
    omega
  · -- kind 6: pattern_p1_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hs0, hs1, hs2, hs3, hs4, hs5, hs6, hs7, hs8, hb0, hb1, hb2, hb3, hb4, hb5⟩ := hkill
    have hm8 : ∀ t, t < 7 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 7 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_p1_impossible hX (c := qf p (fld cert 6))
      (u := fun k : Fin 6 => qf p (fld cert k.val)) (hqmem _) (fun i => hqmem _)
      ?_ ?_ (hqdist hs0) (hqdist hs1) (hqdist hs2) (hqdist hs3) (hqdist hs4) (hqdist hs5) (hqdist hs6) (hqdist hs7) (hqdist hs8)
    · intro a b hab
      by_contra hne
      have ha6 := a.isLt
      have hb6 := b.isLt
      have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
      rcases Nat.lt_or_ge a.val b.val with h | h
      · exact hqne (hm8 _ (by omega)) (hm8 _ (by omega))
          (hmne b.val a.val (by omega) h) hab.symm
      · have h' : b.val < a.val := by omega
        exact hqne (hm8 _ (by omega)) (hm8 _ (by omega))
          (hmne a.val b.val (by omega) h') hab
    · intro i
      fin_cases i
      · rw [dist_comm]; exact hqdist hb0
      · rw [dist_comm]; exact hqdist hb1
      · rw [dist_comm]; exact hqdist hb2
      · rw [dist_comm]; exact hqdist hb3
      · rw [dist_comm]; exact hqdist hb4
      · rw [dist_comm]; exact hqdist hb5
  · -- kind 7: pattern_p4_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hs0, hs1, hs2, hs3, hs4, hs5, hs6, hs7, hs8, hb0, hb1, hb2, hb3, hb4, hb5⟩ := hkill
    have hm8 : ∀ t, t < 7 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 7 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_p4_impossible hX (c := qf p (fld cert 6))
      (u := fun k : Fin 6 => qf p (fld cert k.val)) (hqmem _) (fun i => hqmem _)
      ?_ ?_ (hqdist hs0) (hqdist hs1) (hqdist hs2) (hqdist hs3) (hqdist hs4) (hqdist hs5) (hqdist hs6) (hqdist hs7) (hqdist hs8)
    · intro a b hab
      by_contra hne
      have ha6 := a.isLt
      have hb6 := b.isLt
      have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
      rcases Nat.lt_or_ge a.val b.val with h | h
      · exact hqne (hm8 _ (by omega)) (hm8 _ (by omega))
          (hmne b.val a.val (by omega) h) hab.symm
      · have h' : b.val < a.val := by omega
        exact hqne (hm8 _ (by omega)) (hm8 _ (by omega))
          (hmne a.val b.val (by omega) h') hab
    · intro i
      fin_cases i
      · rw [dist_comm]; exact hqdist hb0
      · rw [dist_comm]; exact hqdist hb1
      · rw [dist_comm]; exact hqdist hb2
      · rw [dist_comm]; exact hqdist hb3
      · rw [dist_comm]; exact hqdist hb4
      · rw [dist_comm]; exact hqdist hb5
  · -- kind 8: pattern_p5_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hs0, hs1, hs2, hs3, hs4, hs5, hs6, hs7, hs8, hb0, hb1, hb2, hb3, hb4⟩ := hkill
    have hm8 : ∀ t, t < 7 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 7 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_p5_impossible hX (c := qf p (fld cert 6))
      (u := fun k : Fin 6 => qf p (fld cert k.val)) (hqmem _) (fun i => hqmem _)
      ?_ (hqne (hm8 0 (by omega)) (hm8 6 (by omega))
        (hmne 6 0 (by omega) (by omega)).symm)
      (by rw [dist_comm]; exact hqdist hb0) (by rw [dist_comm]; exact hqdist hb1) (by rw [dist_comm]; exact hqdist hb2) (by rw [dist_comm]; exact hqdist hb3) (by rw [dist_comm]; exact hqdist hb4)
      (hqdist hs0) (hqdist hs1) (hqdist hs2) (hqdist hs3) (hqdist hs4) (hqdist hs5) (hqdist hs6) (hqdist hs7) (hqdist hs8)
    · intro a b hab
      by_contra hne
      have ha6 := a.isLt
      have hb6 := b.isLt
      have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
      rcases Nat.lt_or_ge a.val b.val with h | h
      · exact hqne (hm8 _ (by omega)) (hm8 _ (by omega))
          (hmne b.val a.val (by omega) h) hab.symm
      · have h' : b.val < a.val := by omega
        exact hqne (hm8 _ (by omega)) (hm8 _ (by omega))
          (hmne a.val b.val (by omega) h') hab
  · -- kind 9: canonicity violation (lex-max enumeration dominated)
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hi36, hpre, hnsi, hesi⟩ := hkill
    have hm9 : ∀ t, t < 9 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 9 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    set i := fld cert 9 + 16 * fld cert 10 with hidef
    set π : Fin 9 → Fin 9 :=
      fun t => ⟨fld cert t.val % 9, Nat.mod_lt _ (by norm_num)⟩ with hπ
    have hπinj : Function.Injective π := by
      intro a b hab
      by_contra hne
      have ha9 := a.isLt
      have hb9 := b.isLt
      have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
      have hva : fld cert a.val < 9 := hm9 _ (by omega)
      have hvb : fld cert b.val < 9 := hm9 _ (by omega)
      have hveq : fld cert a.val = fld cert b.val := by
        have h2 := congrArg Fin.val hab
        simpa [hπ, Nat.mod_eq_of_lt hva, Nat.mod_eq_of_lt hvb] using h2
      rcases Nat.lt_or_ge a.val b.val with h | h
      · exact hmne b.val a.val (by omega) h hveq.symm
      · exact hmne a.val b.val (by omega) (by omega) hveq
    set q' : Fin 9 → E3 := fun t => p (π t) with hq'
    have hq'inj : Function.Injective q' := fun a b hab => hπinj (hpinj hab)
    have hq'im : Finset.image q' Finset.univ = X := by
      rw [← hXim]
      apply Finset.eq_of_subset_of_card_le
      · intro w hw
        obtain ⟨t, _, rfl⟩ := Finset.mem_image.mp hw
        exact Finset.mem_image.mpr ⟨π t, Finset.mem_univ _, rfl⟩
      · rw [Finset.card_image_of_injective _ hpinj,
          Finset.card_image_of_injective _ hq'inj]
    have hbes : ∀ j ∈ es, bbit p j = 1 := by
      intro j hj
      unfold bbit
      rw [if_pos]
      exact (hes j hj).2
    have hbns : ∀ j ∈ ns, bbit p j = 0 := by
      intro j hj
      unfold bbit
      rw [if_neg]
      exact (hns j hj).2
    have himg : ∀ j, j < 36 → cPairFst j < 9 → cPairSnd j < 9 →
        cPairFst j ≠ cPairSnd j →
        fld cert (cPairFst j) ≠ fld cert (cPairSnd j) →
        bbit q' j
          = bbit p (pairIdx9 (fld cert (cPairFst j)) (fld cert (cPairSnd j))) := by
      intro j hj hf hs hne hfe
      have hf9 : fld cert (cPairFst j) < 9 := hm9 _ hf
      have hg9 : fld cert (cPairSnd j) < 9 := hm9 _ hs
      obtain ⟨hidx, hmin, hmax'⟩ := pair_codec _ hf9 _ hg9 hfe
      unfold bbit
      have hq'a : q' ⟨cPairFst j % 9, Nat.mod_lt _ (by norm_num)⟩
          = p ⟨fld cert (cPairFst j) % 9, Nat.mod_lt _ (by norm_num)⟩ := by
        simp only [hq', hπ]
        congr 2
        rw [Nat.mod_eq_of_lt hf]
      have hq'b : q' ⟨cPairSnd j % 9, Nat.mod_lt _ (by norm_num)⟩
          = p ⟨fld cert (cPairSnd j) % 9, Nat.mod_lt _ (by norm_num)⟩ := by
        simp only [hq', hπ]
        congr 2
        rw [Nat.mod_eq_of_lt hs]
      rw [hq'a, hq'b]
      have hkey : ∀ a b : ℕ, a < 9 → b < 9 → a ≠ b →
          cPairFst (pairIdx9 a b) = min a b → cPairSnd (pairIdx9 a b) = max a b →
          (if dist (p ⟨a % 9, Nat.mod_lt _ (by norm_num)⟩)
                (p ⟨b % 9, Nat.mod_lt _ (by norm_num)⟩) = 1 then 1 else 0)
          = (if dist (p ⟨cPairFst (pairIdx9 a b) % 9, Nat.mod_lt _ (by norm_num)⟩)
                (p ⟨cPairSnd (pairIdx9 a b) % 9, Nat.mod_lt _ (by norm_num)⟩) = 1
             then 1 else 0) := by
        intro a b ha hb hne2 hmn hmx
        have hcf : cPairFst (pairIdx9 a b) = min a b := hmn
        have hcs : cPairSnd (pairIdx9 a b) = max a b := hmx
        rw [hcf, hcs]
        rcases le_total a b with hle | hle
        · rw [min_eq_left hle, max_eq_right hle]
        · rw [min_eq_right hle, max_eq_left hle]
          rw [dist_comm]
      exact hkey _ _ hf9 hg9 hfe hmin hmax'
    have hi36' : i < 36 := hi36
    have hfldne : ∀ j, j < 36 → fld cert (cPairFst j) ≠ fld cert (cPairSnd j) := by
      intro j hj
      obtain ⟨hflt, hs9⟩ := pair_decode_lt j hj
      intro h
      exact hmne (cPairSnd j) (cPairFst j) (by omega) (by omega) h.symm
    have hagree : ∀ j < i, bbit p j = bbit q' j := by
      intro j hj
      have hp2 := hpre j hj
      try simp only [Bool.or_eq_true, Bool.and_eq_true, List.contains_iff_mem] at hp2
      have hj36 : j < 36 := by omega
      obtain ⟨hflt, hs9⟩ := pair_decode_lt j hj36
      have heq := himg j hj36 (by omega) (by omega) (by omega) (hfldne j hj36)
      rcases hp2 with ⟨hj1, hj2⟩ | ⟨hj1, hj2⟩
      · rw [hbes j hj1, heq, hbes _ hj2]
      · rw [hbns j hj1, heq, hbns _ hj2]
    have hstrict : bbit p i < bbit q' i := by
      obtain ⟨hflt, hs9⟩ := pair_decode_lt i hi36'
      have heq := himg i hi36' (by omega) (by omega) (by omega) (hfldne i hi36')
      have hns2 : i ∈ ns := by
        simpa [List.contains_iff_mem] using hnsi
      have hes2 : pairIdx9 (fld cert (cPairFst i)) (fld cert (cPairSnd i)) ∈ es := by
        simpa [List.contains_iff_mem] using hesi
      rw [hbns i hns2, heq, hbes _ hes2]
      norm_num
    have hlt := bondCode_lt hi36' hagree hstrict
    have hle := hmax q' hq'inj hq'im
    omega
  · -- kind 10: pattern_p6_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10⟩ := hkill
    have hm9 : ∀ t, t < 6 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 6 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_p6_impossible hX (q := fun k : Fin 6 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 11: pattern_obs7_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13⟩ := hkill
    have hm9 : ∀ t, t < 7 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 7 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_obs7_impossible hX (q := fun k : Fin 7 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 12: pattern_obs3_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13⟩ := hkill
    have hm9 : ∀ t, t < 7 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 7 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_obs3_impossible hX (q := fun k : Fin 7 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 13: pattern_obs0_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13⟩ := hkill
    have hm9 : ∀ t, t < 7 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 7 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_obs0_impossible hX (q := fun k : Fin 7 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 14: pattern_class23_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13, hb14, hb15, hb16, hb17, hb18, hb19, hb20, hb21⟩ := hkill
    have hm9 : ∀ t, t < 9 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 9 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_class23_impossible hX (q := fun k : Fin 9 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13) (hqdist hb14) (hqdist hb15) (hqdist hb16) (hqdist hb17) (hqdist hb18) (hqdist hb19) (hqdist hb20) (hqdist hb21)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 15: pattern_q0_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13, hb14, hb15, hb16, hb17⟩ := hkill
    have hm9 : ∀ t, t < 8 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 8 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_q0_impossible hX (q := fun k : Fin 8 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13) (hqdist hb14) (hqdist hb15) (hqdist hb16) (hqdist hb17)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 16: pattern_q4_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13, hb14, hb15, hb16, hb17⟩ := hkill
    have hm9 : ∀ t, t < 8 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 8 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_q4_impossible hX (q := fun k : Fin 8 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13) (hqdist hb14) (hqdist hb15) (hqdist hb16) (hqdist hb17)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 17: pattern_q10_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13, hb14, hb15, hb16, hb17⟩ := hkill
    have hm9 : ∀ t, t < 8 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 8 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_q10_impossible hX (q := fun k : Fin 8 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13) (hqdist hb14) (hqdist hb15) (hqdist hb16) (hqdist hb17)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 18: pattern_q1_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13, hb14, hb15, hb16, hb17⟩ := hkill
    have hm9 : ∀ t, t < 8 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 8 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_q1_impossible hX (q := fun k : Fin 8 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13) (hqdist hb14) (hqdist hb15) (hqdist hb16) (hqdist hb17)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 19: pattern_q12_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13, hb14, hb15, hb16, hb17⟩ := hkill
    have hm9 : ∀ t, t < 8 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 8 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_q12_impossible hX (q := fun k : Fin 8 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13) (hqdist hb14) (hqdist hb15) (hqdist hb16) (hqdist hb17)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 20: pattern_q28_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13, hb14, hb15, hb16⟩ := hkill
    have hm9 : ∀ t, t < 8 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 8 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_q28_impossible hX (q := fun k : Fin 8 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13) (hqdist hb14) (hqdist hb15) (hqdist hb16)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 21: pattern_q30_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13, hb14, hb15, hb16, hb17⟩ := hkill
    have hm9 : ∀ t, t < 8 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 8 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_q30_impossible hX (q := fun k : Fin 8 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13) (hqdist hb14) (hqdist hb15) (hqdist hb16) (hqdist hb17)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- kind 22: pattern_q37_impossible
    simp only [checkCert, hk] at hkill
    norm_num at hkill
    simp only [Bool.and_eq_true, and_assoc] at hkill
    obtain ⟨hall1, hall2, hb0, hb1, hb2, hb3, hb4, hb5, hb6, hb7, hb8, hb9, hb10, hb11, hb12, hb13, hb14, hb15, hb16, hb17⟩ := hkill
    have hm9 : ∀ t, t < 8 → fld cert t < 9 := fun t ht => hall1 t ht
    have hmne : ∀ t t', t < 8 → t' < t → fld cert t ≠ fld cert t' :=
      fun t t' ht ht' => hall2 t ht t' ht'
    refine pattern_q37_impossible hX (q := fun k : Fin 8 => qf p (fld cert k.val)) (fun i => hqmem _) ?_ (hqdist hb0) (hqdist hb1) (hqdist hb2) (hqdist hb3) (hqdist hb4) (hqdist hb5) (hqdist hb6) (hqdist hb7) (hqdist hb8) (hqdist hb9) (hqdist hb10) (hqdist hb11) (hqdist hb12) (hqdist hb13) (hqdist hb14) (hqdist hb15) (hqdist hb16) (hqdist hb17)
    intro a b hab
    by_contra hne
    have ha6 := a.isLt
    have hb6 := b.isLt
    have hne' : a.val ≠ b.val := fun h => hne (Fin.ext h)
    rcases Nat.lt_or_ge a.val b.val with h | h
    · exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne b.val a.val (by omega) h) hab.symm
    · have h' : b.val < a.val := by omega
      exact hqne (hm9 _ (by omega)) (hm9 _ (by omega))
        (hmne a.val b.val (by omega) h') hab
  · -- impossible kind
    have hK0 : cert % 64 ≠ 0 := by omega
    have hK1 : cert % 64 ≠ 1 := by omega
    have hK2 : cert % 64 ≠ 2 := by omega
    have hK3 : cert % 64 ≠ 3 := by omega
    have hK4 : cert % 64 ≠ 4 := by omega
    have hK5 : cert % 64 ≠ 5 := by omega
    have hK6 : cert % 64 ≠ 6 := by omega
    have hK7 : cert % 64 ≠ 7 := by omega
    have hK8 : cert % 64 ≠ 8 := by omega
    have hK9 : cert % 64 ≠ 9 := by omega
    have hK10 : cert % 64 ≠ 10 := by omega
    have hK11 : cert % 64 ≠ 11 := by omega
    have hK12 : cert % 64 ≠ 12 := by omega
    have hK13 : cert % 64 ≠ 13 := by omega
    have hK14 : cert % 64 ≠ 14 := by omega
    have hK15 : cert % 64 ≠ 15 := by omega
    have hK16 : cert % 64 ≠ 16 := by omega
    have hK17 : cert % 64 ≠ 17 := by omega
    have hK18 : cert % 64 ≠ 18 := by omega
    have hK19 : cert % 64 ≠ 19 := by omega
    have hK20 : cert % 64 ≠ 20 := by omega
    have hK21 : cert % 64 ≠ 21 := by omega
    have hK22 : cert % 64 ≠ 22 := by omega
    simp [checkCert, beq_iff_eq, hK0, hK1, hK2, hK3, hK4, hK5, hK6, hK7, hK8, hK9, hK10, hK11, hK12, hK13, hK14, hK15, hK16, hK17, hK18, hK19, hK20, hK21, hK22] at hkill

open scoped Classical in
/-- **Walk soundness**: a successful walk of any kill tree is incompatible with a
hard-core eight-particle realization carrying 38 ordered contacts. The branch at pair
`k` is decided by the realization itself. -/
theorem walk_impossible {X : Finset E3} (hX : HardCore X) {p : Fin 9 → E3}
    (hpmem : ∀ i, p i ∈ X) (hpinj : Function.Injective p)
    (h9 : X.card = 9) (hXim : Finset.image p Finset.univ = X)
    (hcc : 43 ≤ contactCount X)
    (hmax : ∀ q : Fin 9 → E3, Function.Injective q → Finset.image q Finset.univ = X → bondCode q ≤ bondCode p) :
    ∀ (fuel : ℕ) (data : List ℕ) (k : ℕ) (es ns rest : List ℕ),
    walk fuel data k es ns = some rest →
    (∀ i ∈ es, i < 36 ∧ dist (qf p (cPairFst i)) (qf p (cPairSnd i)) = 1) →
    (∀ i ∈ ns, i < 36 ∧ ¬ dist (qf p (cPairFst i)) (qf p (cPairSnd i)) = 1) →
    es.Nodup → ns.Nodup → (∀ i ∈ es, i < k) → (∀ i ∈ ns, i < k) → False := by
  intro fuel
  induction fuel with
  | zero =>
    intro data k es ns rest hwalk hes hns hesnd hnsnd heslt hnslt
    simp [walk] at hwalk
  | succ fuel ih =>
    intro data k es ns rest hwalk hes hns hesnd hnsnd heslt hnslt
    match data with
    | [] => simp [walk] at hwalk
    | c :: rest' =>
      rw [show walk (fuel + 1) (c :: rest') k es ns
          = (if c == 0 then
              if k < 36 then
                match walk fuel rest' (k + 1) (k :: es) ns with
                | none => none
                | some rest2 => walk fuel rest2 (k + 1) es (k :: ns)
              else none
            else if checkCert es ns ((c - 1) / 2) then some rest'
            else none) from rfl] at hwalk
      by_cases hc : c == 0
      · rw [if_pos hc] at hwalk
        by_cases hklt : k < 36
        · rw [if_pos hklt] at hwalk
          by_cases hbond : dist (qf p (cPairFst k)) (qf p (cPairSnd k)) = 1
          · cases hw : walk fuel rest' (k + 1) (k :: es) ns with
            | none => rw [hw] at hwalk; simp at hwalk
            | some rest2 =>
              refine ih rest' (k + 1) (k :: es) ns rest2 hw ?_ hns ?_ hnsnd ?_
                (fun i hi => Nat.lt_succ_of_lt (hnslt i hi))
              · intro i hi
                rcases List.mem_cons.mp hi with rfl | hi
                · exact ⟨hklt, hbond⟩
                · exact hes i hi
              · refine List.nodup_cons.mpr ⟨?_, hesnd⟩
                intro hmem
                exact absurd (heslt k hmem) (lt_irrefl k)
              · intro i hi
                rcases List.mem_cons.mp hi with rfl | hi
                · omega
                · exact Nat.lt_succ_of_lt (heslt i hi)
          · cases hw : walk fuel rest' (k + 1) (k :: es) ns with
            | none => rw [hw] at hwalk; simp at hwalk
            | some rest2 =>
              rw [hw] at hwalk
              simp only at hwalk
              refine ih rest2 (k + 1) es (k :: ns) rest hwalk hes ?_ hesnd ?_
                (fun i hi => Nat.lt_succ_of_lt (heslt i hi)) ?_
              · intro i hi
                rcases List.mem_cons.mp hi with rfl | hi
                · exact ⟨hklt, hbond⟩
                · exact hns i hi
              · refine List.nodup_cons.mpr ⟨?_, hnsnd⟩
                intro hmem
                exact absurd (hnslt k hmem) (lt_irrefl k)
              · intro i hi
                rcases List.mem_cons.mp hi with rfl | hi
                · omega
                · exact Nat.lt_succ_of_lt (hnslt i hi)
        · rw [if_neg hklt] at hwalk
          simp at hwalk
      · rw [if_neg hc] at hwalk
        by_cases hcert : checkCert es ns ((c - 1) / 2) = true
        · exact checkCert_sound hX hpmem hpinj h9 hXim hcc hmax hes hns hesnd hnsnd hcert
        · rw [if_neg hcert] at hwalk
          simp at hwalk

open scoped Classical in
/-- **The finite fact, parametrized by a verified kill tree**: any serialized tree
accepted by `walk` bounds every hard-core eight-particle configuration at 36 ordered
contacts. -/
theorem nine_particle_bound_of_tree {fuel : ℕ} {data : List ℕ}
    (htree : walk fuel data 0 [] [] = some [])
    {X : Finset E3} (hX : HardCore X) (h9 : X.card = 9) : contactCount X ≤ 42 := by
  by_contra hcon
  push_neg at hcon
  obtain ⟨m, hm⟩ := contactCount_even X
  have hcc : 43 ≤ contactCount X := by omega
  obtain ⟨p, hpinj, hXim, hmax⟩ := exists_lexmax_enum h9
  have hpmem : ∀ i, p i ∈ X := by
    intro i
    rw [← hXim]
    exact Finset.mem_image.mpr ⟨i, Finset.mem_univ i, rfl⟩
  exact walk_impossible hX hpmem hpinj h9 hXim hcc hmax
    fuel data 0 [] [] [] htree
    (by simp) (by simp) (by simp) (by simp) (by simp) (by simp)

/-- Fuel monotonicity: extra fuel never hurts a successful walk. -/
lemma walk_fuel_mono {f f' : ℕ} (hf : f ≤ f') :
    ∀ {d : List ℕ} {k : ℕ} {es ns r : List ℕ},
    walk f d k es ns = some r → walk f' d k es ns = some r := by
  induction f' generalizing f with
  | zero =>
    intro d k es ns r h
    interval_cases f
    simp [walk] at h
  | succ f' ih =>
    intro d k es ns r h
    match f, h with
    | 0, h => simp [walk] at h
    | f + 1, h =>
      have hff : f ≤ f' := by omega
      match d with
      | [] => simp [walk] at h
      | c :: rest =>
        rw [show walk (f + 1) (c :: rest) k es ns
            = (if c == 0 then
                if k < 36 then
                  match walk f rest (k + 1) (k :: es) ns with
                  | none => none
                  | some rest2 => walk f rest2 (k + 1) es (k :: ns)
                else none
              else if checkCert es ns ((c - 1) / 2) then some rest else none) from rfl] at h
        rw [show walk (f' + 1) (c :: rest) k es ns
            = (if c == 0 then
                if k < 36 then
                  match walk f' rest (k + 1) (k :: es) ns with
                  | none => none
                  | some rest2 => walk f' rest2 (k + 1) es (k :: ns)
                else none
              else if checkCert es ns ((c - 1) / 2) then some rest else none) from rfl]
        by_cases hc : c == 0
        · rw [if_pos hc] at h ⊢
          by_cases hk : k < 36
          · rw [if_pos hk] at h ⊢
            cases hw : walk f rest (k + 1) (k :: es) ns with
            | none => rw [hw] at h; simp at h
            | some rest2 =>
              rw [hw] at h
              simp only at h
              rw [ih hff hw]
              simpa using ih hff h
          · rw [if_neg hk] at h
            exact absurd h (by simp)
        · rw [if_neg hc] at h ⊢
          exact h

/-- Symbolic branch composition for chunked kernel checks. -/
lemma walk_branch {fuel : ℕ} {dL dR : List ℕ} {k : ℕ} {es ns : List ℕ}
    (hk : k < 36)
    (hL : walk fuel dL (k + 1) (k :: es) ns = some [])
    (hR : walk fuel dR (k + 1) es (k :: ns) = some []) :
    walk (fuel + 1) ((0 : ℕ) :: (dL ++ dR)) k es ns = some [] := by
  have hcomp := walk_append (l2 := dR) hL
  rw [List.nil_append] at hcomp
  rw [show walk (fuel + 1) ((0 : ℕ) :: (dL ++ dR)) k es ns
      = (if (0 : ℕ) == 0 then
          if k < 36 then
            match walk fuel (dL ++ dR) (k + 1) (k :: es) ns with
            | none => none
            | some rest2 => walk fuel rest2 (k + 1) es (k :: ns)
          else none
        else if checkCert es ns (((0 : ℕ) - 1) / 2) then some (dL ++ dR)
        else none) from rfl]
  rw [if_pos (by norm_num), if_pos hk, hcomp]
  simpa using hR

end Emin9T

end Kissing3D
